### ISSUE TITLE
Кол-во комментариев появляется позже слова "комментариев"

### ISSUE THREAD

**Issue by atomAltera** [radio-t/radio-t-site#104]
При загрузке страницы, везде где отображается число комментариев, сначала оботражается только слово "комментариев", а потом, уже "X комментариев".

Демонстрация: https://youtu.be/7leUZkUCoHc

Предлогаю вообще не показывать слово "комментариев" пока кол-во комментариев не будет доступно.

**Comment by umputun** [comment]
это настолько минорный и безобидный эффект, что я предлагаю не заморачиваться его починкой, если починка займет больше 5 минут.
