### ISSUE TITLE
при наведении на текст мышью, подсвечивается блок - помимо изменения цвета самого текста

### ISSUE THREAD

**Issue by keRin7** [radio-t/radio-t-site#110]
![image](https://user-images.githubusercontent.com/20859433/67276250-78f18a00-f4ee-11e9-8353-f37e5df2fcdd.png)

я не уверен что это баг, может быть так и задумано, 
либо действительно баг бэкграунд элемента при наведении не соответствует цвету фона(отвязан от цвета фона).
но без выделенных квадратных блоков, когда мышью водишь по ссылкам - смотрелось бы помягче/получше.

**Comment by sw-double** [comment]
спасибо. это не баг :) возможно, в темной теме стоит "поиграть цветами"
