### ISSUE TITLE
Проблемы с отображением navbar в маленьком viewport (Chrome)

### ISSUE THREAD

**Issue by bulatenkom** [radio-t/radio-t-site#112]
**Проблема**: В браузере Chrome есть проблемы с отображением навигационного меню при маленьких значениях viewport. См. скрины.

**Пример проблемы**:

Browser: Chrome / Version 78.0.3904.87 (Official Build) (64-bit)

<div align=center>
<img src="https://user-images.githubusercontent.com/16873338/68042607-e62ec780-fd05-11e9-9892-7db539693be1.png" width="400">
</div>

<hr>

Browser: Android Chrome / Version 78.0.3904.62

<div align=center>
<img src="https://user-images.githubusercontent.com/16873338/68042799-5a696b00-fd06-11e9-946a-05a8c945a05d.png" width="300">
</div>

<hr>

**В других браузерах все в порядке**:

Browser: Safari / Version 12.1.2 (14607.3.9)

<div align=center>
<img src="https://user-images.githubusercontent.com/16873338/68043277-7de0e580-fd07-11e9-937e-d0708a019cc7.png" width="400">
</div>

<hr>

Browser: Firefox / Version 70.0.1 (64-bit)

<div align=center>
<img src="https://user-images.githubusercontent.com/16873338/68043370-b54f9200-fd07-11e9-894b-c20f62c08d65.png" width="400">
</div>

<hr>

В прочих других мобильных браузерах не Chrome(Blink)-base все работает как положено.

**Comment by sw-double** [comment]
@bulatenkom спасибо!
