### ISSUE TITLE
Дата и время наезжают на комментарий

### ISSUE THREAD

**Issue by anikinmd** [radio-t/radio-t-site#121]
Проблема в темах к выпуску и в комментариях под выпуском.
При просмотре с телефона (или при достаточном сужении окна сайта), дата и время перемещаются под имя комментатора и наезжают на сам комментарий.
![98ECF07B-44D7-446D-ADA7-F33273B653A6](https://user-images.githubusercontent.com/50917015/72413321-9c8c3f80-3780-11ea-943a-5165a1cfc6ee.png)

**Comment by akellbl4** [comment]
@anikinmd пофикшено
