### ISSUE TITLE
обновить картинку

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#127]
<img width="310" alt="1jwna-202002-01133011-yz1xi" src="https://user-images.githubusercontent.com/535880/73597933-4dbc0500-44f7-11ea-82e9-427827129e6e.png">

больше не соответствует. код теперь radiot и сумма $100

**Comment by sw-double** [comment]
@eshill посмотри, плиз

**Comment by Khilkov** [comment]
[DO.svg.zip](https://github.com/radio-t/radio-t-site/files/4143177/DO.svg.zip)

**Comment by umputun** [comment]
поменял. спасибо
