### ISSUE TITLE
Онлайн вещание в AAC формате (48-64 kbps)

### ISSUE THREAD

**Issue by zedxxx** [radio-t/radio-t-site#133]
Возможно ли добавить альтернативный поток вещания с низким битрейтом? Было бы замечательно для случаев, когда под рукой есть только медленный и/или дорогой мобильный интернет.

Примеры звучания:
- музыка (Радио Атмосфера) http://185.53.169.128:8000/64.m3u (AAC+ 64kbps, stereo)
- разговоры (Эхо Москвы) http://ice912.echo.msk.ru:9120/32.aac (AAC 32kbps, stereo)

Судя по вот [этому](https://www.articlecity.com/articles/music_and_movies/article_1030.shtml) анализу, формат AAC+ предпочтительнее простому AAC на битрейтах до 64kbps.

**Comment by umputun** [comment]
вещание AAC в дополнение к mp3 потоку требует определенной, и нетривиальной переконфигурации всего кластера. И еще требует посылать второй поток.

Все это, в принципе, делается. Однако подобное изменение долюно быть оправдано. Последние 10 лет я не слышал жалоб "не хватает интернета для получения подкаста". Кроме того, это подкаст и его можно послушать посел выхода, загрузив в любой подкаст клиент при любой скорости интернета.
