### ISSUE TITLE
Netlify mirror indexing

### ISSUE THREAD

**Issue by paskal** [radio-t/radio-t-site#141]
Hi there!

I was testing comments search for umputun/remark42/issues/585 and found that dev netlify app is in the search indexes.

[<img width="927" alt="image" src="https://user-images.githubusercontent.com/712534/80337430-19d44f80-885a-11ea-8912-ca7aca3ebdaa.png">](https://www.google.com/search?client=firefox-b-d&q=%22Microsoft+%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D0%BB+%D1%81%D0%B2%D0%BE%D0%B9+Spotlight%22)

Would it be possible to hide it using robots.txt to prevent confusion with the site?

**Comment by paskal** [comment]
Ping @webkonstantin.

**Comment by akellbl4** [comment]
@paskal мне говорили тут можно на русском писать :)

**Comment by webkonstantin** [comment]
удалил, спасибо
