### ISSUE TITLE
Не работают комментарии локально

### ISSUE THREAD

**Issue by webkonstantin** [radio-t/radio-t-site#173]
можно добавить localhost в `Content-Security-Policy: frame-ancestors`?

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/2104054/104122539-92caf700-5356-11eb-9c34-33baf028077a.png">

**Comment by umputun** [comment]
это был результат забытого эксперимента, который мы проводили до того, как добавили нормальную поддержку frame-ancestors в комментах. Починил.
