### ISSUE TITLE
Сломана подгрузка комментариев

### ISSUE THREAD

**Issue by stanislavshabalin** [radio-t/radio-t-site#182]
На всех страницах бесконечный лоадер комментов (пример — https://radio-t.com/p/2021/01/09/podcast-736/), похоже на фронт, т.к. в инспекторе запросы на урлы с undefined в середине, пример:
`[Error] Failed to load resource: the server responded with a status of 404 () (config, line 0) https://remark42.radio-t.com/web/undefined/api/v1/config?site=radiot`

Воспроизводится как минимум в Safari, Firefox и на iOS.

Upd: похоже, что, скорее, на стороне Ремарка (хотя может и проблема в конфигурации). Воспроизводится из [iFrame на https://remark42.radio-t.com](https://remark42.radio-t.com/web/iframe.html?baseurl=https%3A%2F%2Fremark42.radio-t.com&site_id=radiot&page_title=%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%20736&theme=dark&locale=ru&url=https%3A%2F%2Fradio-t.com%2Fp%2F2021%2F01%2F09%2Fpodcast-736%2F), но дальше из минифицированного JS уже не подебажить.

**Comment by umputun** [comment]
да, спасибо. У нас тут обновления выходят, неожиданно кое-что поломали. Уже чиним

**Comment by stanislavshabalin** [comment]
Вижу, что всё уже заработало обратно, большое спасибо! 👍

**Comment by stanislavshabalin** [comment]
На десктопе заработало, а вот на iOS что-то ещё отвалилось — текст не рендерится.

**Comment by umputun** [comment]
подозреваю твой кеш, у себя проблемы не наблюдаю
