### ISSUE TITLE
С 739 выпуска сломались главы (chapters)

### ISSUE THREAD

**Issue by Rakleed** [radio-t/radio-t-site#209]
С 739 выпуска сломались главы (chapters) — в Apple Podcasts и Pocket Casts они не отображаются. А Overcast видимо сам делает главы с помощью timestamps из описания.

<details>
<summary>Скриншоты</summary>

![Image-1](https://user-images.githubusercontent.com/19418601/108692757-10655380-750e-11eb-8fe9-4873873cc91c.png)

![Image-3](https://user-images.githubusercontent.com/19418601/108692761-11968080-750e-11eb-9a34-b2acf2c55b53.png)

</details>

@q210 не могли бы вы, пожалуйста, посмотреть, в чём может быть проблема?

**Comment by q210** [comment]
Добрый день, действительно что-то где-то отломалось, большое спасибо за сигнал.

Починю.

**Comment by q210** [comment]
хм, в 743м эпизоде главы вновь показываются в Podcasts на маке и в iOS, при том что я ничего не делал еще (попытался воспроизвести проблему в понедельник, увидел что действительно нет глав в последних выпусках, оставил на выходные когда время будет).

Все страньше и страньше, пора призывать аксакалов.

@umputun подскажи плз - ничего не менялось в процессе релиза между 742 и 743 ? В коммитах ничего подозрительного не вижу.

Если в процессе релиза ничего не менялось, следующая теория - в тексте описания, который парсится скриптами для создания разметки глав, буду копать туда.

**Comment by umputun** [comment]
нет, я ничего не чинил. Там, судя по всему, что то падает в зависимости от тем выпуска. Я не это обращал внимания когда выкладывал в tg:

<img width="659" alt="fy4gv-202102-28132455-vb2wa" src="https://user-images.githubusercontent.com/535880/109430709-5ae04780-79c8-11eb-98c8-017b9bb77d99.png">

**Comment by q210** [comment]
ok, экспериментальным путем установил, что Apple не нравится используемая нами версия стандарта ID3 тэгов. 

Мы используем ID3v2.4, от 2003го года (https://id3.org/id3v2.4.0-frames), и любые названия глав длиннее 51 юникодного символа ломают отображение глав в Podcasts на MacOS и iOS.

Переформатировал теже оглавления в форматID3v2.4, от 1999го года (https://id3.org/id3v2.3.0) и ограничение на длинну пропало.

**Comment by q210** [comment]
@umputun фикс из pull-request исключит повторение ситуации в будущем, но я не уверен что делать со старыми выпусками. 

Откуда пользователи Podcasts выкачивают mp3 файлы прошлых выпусков? С какого-то CDN? Мы можем перезалить туда файлы, предварительно пересохранив тэги в более старом формате? 

Или слишком много возни, и хватит лишь фикса для будущих выпусков?

**Comment by umputun** [comment]
я могу перезалить, это небольшая проблем.

**Comment by umputun** [comment]
пересобрал и перезалил 742, вроде главы на месте. Не уверен как это просто проверить в podacst но quick view их теперь показывает и tg тоже

**Comment by q210** [comment]
здорово! Тогда надо выполнить команду вида `docker-compose run --rm publisher print-mp3-tags rt_podcast685/rt_podcast685.mp3`

**Comment by umputun** [comment]
для чего?

**Comment by q210** [comment]
сорри, рано отправился комментарий, апдейтнул

**Comment by umputun** [comment]
я имею ввиду, что у меня общее flow которым проще все одним ударом сделать, оно и таги поставит и зальет на все узлы. Запустил для всех до 740 ....

**Comment by umputun** [comment]
все (до 739) перестроил и залил

**Comment by q210** [comment]
@Rakleed у меня после в Podcasts после удаления эпизодов и скачивания их заново главы стали видны, проверь плз тоже

**Comment by Rakleed** [comment]
У меня с 739 по 742 выпуск и в Apple Подкастах, и в Pocket Casts отображаются главы. @q210 и @umputun, спасибо за фикс!
