### ISSUE TITLE
Каменты не транслируются в Телеграм

### ISSUE THREAD

**Issue by NikolayPetyukh** [radio-t/radio-t-site#21]
Вот последние посты на канале:
![image](https://user-images.githubusercontent.com/8134986/49298574-70532800-f4c6-11e8-9df0-b2dd72d82ca9.png)
А вот список последних каментов на сайте:
![image](https://user-images.githubusercontent.com/8134986/49298624-95e03180-f4c6-11e8-9343-fc1f7b23c879.png)

**Comment by umputun** [comment]
починил, добавил кода для предотвращения подобного
