### ISSUE TITLE
Высокая загрузка CPU после запуска проигрывателя

### ISSUE THREAD

**Issue by yuriykashin** [radio-t/radio-t-site#213]
При запуске проигрывателя страница начинает серьезно нагружать процессор.
При паузе чуть полегче, но не сильно (наверное меньше перерисовки).
Возможно не хватает троттлинга при обработке каких-то событий?

**Comment by akellbl4** [comment]
нашел пару возможных виновников:
* обновление прогресса происходит очень часто
* рисовка полосы прогресса происходит с помощью свойства `width` что ведет к частым перерисовкам всей страницы
