### ISSUE TITLE
Часть интерфейса комментариев остается светлой при использовании темной темы

### ISSUE THREAD

**Issue by rakleed** [radio-t/radio-t-site#216]
Часть интерфейса комментариев с информацией о профиле и всех его комментариях остается светлой при использовании темной темы.
<details><summary>Скриншоты</summary>

![ACDF9288-8FEB-44FC-BF0F-D8802C6F8178](https://user-images.githubusercontent.com/19418601/111089600-a0128680-853d-11eb-9018-e56f0e039961.png)

![4D380A13-9FEB-41A0-AA01-609A524B57B0](https://user-images.githubusercontent.com/19418601/111089606-a1dc4a00-853d-11eb-91c8-3fb079a4b0ff.png)

</details>

**Comment by akellbl4** [comment]
Это должно быть адресовано в репозиторий [remark42](https://github.com/umputun/remark42)
