### ISSUE TITLE
Переход на летнее время сломал счетчик до начала

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#217]
это 13:40 CDT, на самом деле до начала подкаст 1ч 20м

<img width="1007" alt="c4vnc-202103-20133924-by1vb" src="https://user-images.githubusercontent.com/535880/111882119-c8591580-8981-11eb-8095-349ed83e2ad2.png">

cc: @webkonstantin

**Comment by webkonstantin** [comment]
что-то никак не могу воспроизвести

**Comment by akellbl4** [comment]
@webkonstantin я просто сменил локальное время на средне американское и воспроизвелось.

**Comment by alexeyten** [comment]
@webkonstantin упс, я всю неделю собирался поиграться =)
