### ISSUE TITLE
Проблемы с google podcasts

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#22]
Поступили жалобы на то, что подкаст пропал из приложения google podcasts. Ситуация непонятная. Согласно [этой статье](https://podnews.net/article/get-your-podcast-onto-google-assistant) подкасты там не имеют ничего общего с подкастами в google music и это косвенно подтверждается тем, что люди находят подписку на архивы которая никогда не была добавлена в music.

Похоже что гугл сам их находит и требует 2х условий:

1. Link to your RSS feed from your website
1. Link to your website from your RSS feed

Насколько я могу судить оба выполнены хотя https://podnews.net/podcast/256504435 (в секции Technical details) утверждает
 
> Google Podcasts: this podcast’s website does not contain a link rel="alternate" element pointing to the RSS feed. This is not following Google’s guidelines. It is, however, listed correctly in Google Podcasts. Use our link badge generator.

Я наблюдаю  rel="alternate" element в фиде:

`<link href="http://feeds.rucast.net/radio-t" title="Радио-Т Подкаст" type="application/atom+xml" rel="alternate">`

Мне такое проверить трудно, т.к. андроида нет под рукой. Если у кого есть идеи, поделитесь.

**Comment by vattghern777** [comment]
1.Что если дело в кодировке или языке внутри тайтла?
2.у меня из Польши все открывает в этом приложении(да и в другом тоже). Может люди жалуются с тех мест, где что-то блокируют?
3.Может само приложение словил ошибку и потому не видит или не подписывает?

**Comment by antonrychkov** [comment]
Подкаст пропал из списка подписок, но при этом в поиске находится и проигрывается.

**Comment by Senpos** [comment]
Сами [подкасты есть](https://i.imgur.com/9hMmO6Y.png). Подписка оформляется, новые выпуски в соотв. разделе появляются и проигрываются.

При этом, на главном экране моя подписка на подкаст [корректно не отображается](https://i.imgur.com/jyi0CjE.png), пишет "Больше не доступен".

Если туда кликнуть - говорят, что [контент недоступен](https://i.imgur.com/6SrTPOZ.png).

**Comment by kalinichenko88** [comment]
Да как-то странно ведет себя приложение. Одновременно посыпались несколько подкастов. Хотя в них можно заходить через ленту В процессе.
Радио-т как-то удалось добавить второй раз. Теперь рядом 2 плитки: живая и недоступная.
Есть еще радио-т архивы. На них не могу подписаться. Кнопка сбрасывается.

**Comment by dkder3k** [comment]
А не может ли быть это все связано с тем, что [вот здесь](https://podnews.net/article/get-your-podcast-onto-google-assistant) в рекомендациях в первом пункте про `Link to your RSS feed from your website` во втором tip-е сказано:
> just make sure it's the same page that you use here and in the next step

А я вижу что на сайте линка согласно правилам есть и она ведет на http://feeds.rucast.net/radio-t
![image](https://user-images.githubusercontent.com/14958281/49401367-09e53880-f758-11e8-8256-81e9ea5a4b46.png)
А в xml link проставляется на https://radio-t.com
![image](https://user-images.githubusercontent.com/14958281/49401649-db1b9200-f758-11e8-8a82-f3ca49eafa66.png)

**Comment by dkder3k** [comment]
А не связано ли это с тем, что в [рекомендациях](https://developers.google.com/search/docs/data-types/podcast#homepage) указано что значение `type` должно быть `application/rss+xml`, а на странице `application/atom+xml`?

**Comment by umputun** [comment]
есть еще вот такое: https://search.google.com/devtools/podcast/preview

если ему дать http://feeds.rucast.net/radio-t то ругается на "This RSS feed is not currently indexed by Google Podcasts". В этом есть определенная ирония, т.к. фид создан другим гугловым сервисом feedburner. Пока не понимаю что ему там не нравится

**Comment by umputun** [comment]
хмм, а вот если дать https://radio-t.com/podcast.rss то принимает, и говорит 

Podcast retrieved. Copy and paste the URL below to link to your podcast and/or share on social media. This link will open directly to your podcast in Google Podcasts, natively throughout Android devices.
https://www.google.com/podcasts?feed=aHR0cHM6Ly9yYWRpby10LmNvbS9wb2RjYXN0LnJzcw%3D%3D

**Comment by abald** [comment]
Проблема носит массовый характер? У себя такого не наблюдаю. [рис.1](https://i.imgur.com/mLDKdmr.jpg) [рис.2](https://i.imgur.com/yJXToq1.jpg)

**Comment by umputun** [comment]
десятки репортов. 

рис2 это не тот подкаст фид о котором идет речь.

**Comment by umputun** [comment]
еще один непонятный факт - если в [Generate a direct link to your podcast](https://search.google.com/devtools/podcast/preview) дать тот-же фид, но на оригинальном домене (http://feeds.feedburner.com/radio-t) то оно его понимает и любит.

**Comment by umputun** [comment]
поддержка отрицает наличие проблемы:

> Thanks for reaching out about your podcast content missing from Google Podcasts app on Android. After review, I'm actually able to see both of your podcasts featured in Google Podcasts app, and I'm also located in California.

**Comment by shpaker** [comment]
> поддержка отрицает наличие проблемы:

Блеск и нищета гугла в полный рост

**Comment by umputun** [comment]
Ожидаю ответа на пояснение проблемы (послал в гугловый сапорт):

- Both attached pictures show archive feeds. Those asr secondary feeds, not the one sites pointing to. The first pic. is for site https://radio-t.com and this site has `<link type="application/rss+xml" rel="alternate" title="Радио-Т Подкаст" href="http://feeds.rucast.net/radio-t”/>`, however the subscription you found is for https://radio-t.com/podcast-archives.rss feed.
- correct feeds are http://feeds.rucast.net/radio-t and http://feeds.rucast.net/umputun
- attempt to put those feeds into link generation tool shows "This RSS feed is not currently indexed by Google Podcasts”
- both feeds generated by google’s feedburner service and worked fine for many years with all podcast aggregators
- both feeds using “My Brand” function (see http://feedburner.google.com/fb/a/mybrand)
- if I put the original feedburner url, i.e. http://feeds.feedburner.com/radio-t into link generation tool, I get "Podcast retrieved …”. This is very strange because both links return **exactly the same content** and feeds.rucast.net is just a CNAME, i.e. `feeds CNAME 1ewd057.feedproxy.ghs.google.com`.
- both podcasts were available before and both became “not available anymore” in your podcast application last week. I guess this is the list of user’s subscriptions.

**Comment by umputun** [comment]
и последнее обновление. Гугл пообещал починить:

> Just to double-check, you want to make sure that these two feeds are featured in Google Podcasts app, yes?
http://feeds.rucast.net/radio-t to replace https://radio-t.com/podcast-archives.rss 
http://feeds.rucast.net/umputun to replace https://podcast.umputun.com/archives.rss
Let me know, and I'll have our team work on updating the canonical URLs for this right away. Sorry about the inconvenience!

Я подтвердил корректность вчера. Те, кто на андоридах - доложите если починилось

**Comment by Senpos** [comment]
На всякий случай - очистил данные приложения, отписался / подписался. 

В ленте подкаст все ещё [отображается как "БОЛЬШЕ НЕДОСТУПЕН"](https://i.imgur.com/7NKEgqV.png). При клике на саму кнопку "БОЛЬШЕ НЕДОСТУПЕН" как и раньше [страница с ошибкой](https://i.imgur.com/LKpftNd.jpg).

Сами подкасты функционируют нормально. История есть, слушать можно.

Возможно, им надо больше времени.

**Comment by umputun** [comment]
> Hi U,
>
>I've gone ahead and escalated this issue, and will provide an update once I have more information. Thanks.

Видимо у них этот процесс занимает время, ждем ...

**Comment by Cigizmoond-Vyhuholev** [comment]
На данный момент активны только архивные, но они со свежими подкастами.

**Comment by dkder3k** [comment]
Шутка или нет, но у меня теперь при попытке поиска не только основной фид радио-т не находит, но и архивный перестал находиться.
![image](https://user-images.githubusercontent.com/14958281/50137099-2da59400-02ab-11e9-99a5-34f90a850111.png)
![image](https://user-images.githubusercontent.com/14958281/50137106-339b7500-02ab-11e9-908b-c8ca3e50e2bf.png)

**Comment by shpaker** [comment]
Ожили подкасты которые были недоступны. Но да, с поиском ерунда какая-то - теперь если искать `Радио-Т`, то вылетят только архивы :)

**Comment by umputun** [comment]
переписка продолжается, на мое последнее письмо получил еще один ответ, в стиле "работа идет, ждите"

> I'm still waiting to see what's going on, and it doesn't look like it's been updated (when I review this). I'll check it out, and provide you an update later this week. Please remember that Google Podcasts app is a Google Search feature, so all of the content that shows up in Google Podcasts app is crawled and indexed. I'll share more information once I hear back about both of the podcasts.

**Comment by ddkedr** [comment]
С последним обновлением приложения Google (9.5.5.21) и Podcast (1.0.0.200631462) наконец-то заработал вывод списка эпизодов Radio-T и UWP в Android Auto!

И в целом, кажется, что все теперь работает как и должно работать, за исключением слова "Архивы" в названии подкаста.

P.S. Не знаю, обращал ли кто-то на это внимание и поможет ли это при дебаге, но Пираты всегда работали корректно.

**Comment by umputun** [comment]
@ddkedr этот тикет именно про то, что фид Архивы  гугл определяет как основной.

**Comment by umputun** [comment]
Получил очередной ответ, и это какой-то абсурд :(

> After much review, it looks like there are issues with the quality of the hosting site that is in violation of Google's webmaster guidelines. Please have them review these guidelines at the following link: https://support.google.com/webmasters/answer/35769?hl=en#3. Thanks again for being patient in waiting for a response, and thanks also for your understanding in this matter.

**Comment by alff0x1f** [comment]
Не знаю насколько актуально, но на данный момент radio-t есть в списке Google podcasts, всё окей.

UWP тоже находится нормально. А вот radio-t archive не нашёл в поиске.

Google Podcasts 1.0.0.266384425
Google 10.93.13.21.arm64
