### ISSUE TITLE
Импорт очень старых коментов

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#23]
До переезда на discuss наши коменты жили в другой систем, IntenseDebate. Я смог выгрузить их XML, однако подобного импортера в remark42 нет, и вряд-ли он там когда-то появится, т.к. IntenseDebate не настолько популярная платформа. 

Наша цель - преобразовать этот xml в json формата backup/restore для remark42.

Вот такой вход:

```
<?xml version="1.0" encoding="UTF-8"?>
<output>

<blogpost>
<url>http%3A%2F%2Fradio-t.com%2Ftemi_dlja_vipuskov%2Ftemyi-dlya-50%2F</url>
<title>Темы для #50</title>
<guid>68</guid>
<comments>
	<comment id='13438060' parentid='13439997'>
		<isAnon>1</isAnon>
		<name><![CDATA[MrZombie]]></name>
		<email>xxxxx@gmail.com</email>
		<url>http://u1304.rpod.ru/</url>
		<ip>0.0.0.0</ip>
		<text><![CDATA[Это фейк???  ]]></text>
		<date>2007-11-23 20:15:56</date>
		<gmt>2007-11-23 20:15:56</gmt>
		<score>0</score>
	</comment>
	<comment id='13439938' parentid='13439989'>
		<isAnon>1</isAnon>
		<name><![CDATA[umputun]]></name>
		<email>umputun@gmail.com</email>
		<url>http://radio-t.com</url>
		<ip>0.0.0.0</ip>
		<text><![CDATA[мы о нем рассказывали с несколько мес. наверное назад. В момент его анонса.  ]]></text>
		<date>2007-09-04 19:30:45</date>
		<gmt>2007-09-04 19:30:45</gmt>
		<score>0</score>
	</comment>
```

Из этого надо сделать типа такого:

```
{"id":"1784445542","pid":"","text":"<p>&gt; онтошения</p>","user":{"name":"paaleksey","id":"disqus_2d5ec74548b6d9e13dcee459f223e09703facf0a","picture":"","admin":false,
"ip":"f407d9a836bb0228ca79bc18bd8ae7fcefb611a0"},"locator":{"site":"radiot","url":"http://radio-t.com/apps/index.html"},"score":0,"votes":{},"time":"2015-01-10T15:09:33
Z"}
{"id":"1894383470","pid":"","text":"<p>Нет возможности скачать приложение для windows phone из Украины(( снимите ограничение, пожалуйста. Смена настроек дала только воз
можность комментарии читать(</p>","user":{"name":"Yaroslav Butcovetc","id":"disqus_5cc13059008be4e9a1ec6cd41a47fa9a100504ab","picture":"","admin":false,"ip":"1b33ef3fee
266591bc9a264210507f8838a9f5cd"},"locator":{"site":"radiot","url":"http://radio-t.com/apps/index.html"},"score":0,"votes":{},"time":"2015-03-08T01:07:26Z"}
{"id":"588398722","pid":"","text":"<p>15.07 9:00-10:40 аудио вчерашнего подкаста недоступно.</p>","user":{"name":"RUVATA","id":"disqus_da39a3ee5e6b4b0d3255bfef95601890a
fd80709","picture":"","admin":false,"ip":"9d8380db5276d67ecab2cc3971430993c659fb97"},"locator":{"site":"radiot","url":"http://radio-t.com/p/2012/07/14/podcast-297/"},"s
core":0,"votes":{},"time":"2012-07-15T06:47:01Z"}
```

Учесть надо следущее:
- `id` и `parentid` стоит модифицировать для того, чтоб избежать возможных коллизий. Можно просто добавить префих, типа `idb_`
- в user.id надо тоже добавить префикс
- ip можно вообще игнорировать
- locator надо строить так, чтоб url показывал на пост и locator.site в `radiot`

Результатом будет скрипт который я смогу запустить у себя. Он не должен быть особо поддерживаемый, т.к. все, что ему надо это сработать один раз. 

UPD:  [добавил исходный файл](https://github.com/radio-t/radio-t-site/files/2673128/IntenseDebate_clean.xml.zip). Теперь мне в виде результата код для преобразования не особо и нужен (разве что по мелкому подправить), но конченый файл.

**Comment by umputun** [comment]
@dev4dev твое решение не соответствует пункту " который я смогу запустить у себя" ;)

```
/Users/umputun/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- nokogiri (LoadError)
	from /Users/umputun/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from convert.rb:1:in `<main>'
```

**Comment by dev4dev** [comment]
@umputun да, забыл добавить пункт `bundle install` в ридми, правда если руби только системный, то возможно надо будет `sudo` вкарячить. давно через `rvm` ставлю, так что даже не знаю

**Comment by umputun** [comment]
```
bundle install
zsh: /Users/umputun/.rvm/gems/ruby-1.9.3-p194/bin/bundle: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin: no such file or directory
Fetching source index from https://rubygems.org/
Could not find mini_portile2-2.3.0 in any of the sources
```
 
было бы круто всего этого приседания избежатъ. Это я на докер намекаю, типа `docker build -t blah` и потом `docker run -it --rm -v ./data:/data blah` было бы совсем хорошо

**Comment by umputun** [comment]
и да, можно результат прямо в stdout, если проще.

**Comment by dev4dev** [comment]
@umputun вроде добавил, правда это первый `Dockerfile` в жизни, может даже заработает

**Comment by umputun** [comment]
поскольку у тебя нет volumes и непонятно где ты вообще из ожидаешь, то стоит поемянть чтоб оно посылало результат на stdout вместо файла, так я смогу это сохранить.

Попытка запуска привела к ошибке:

```
dk run -it --rm rtc input.xml
Traceback (most recent call last):
	1: from convert.rb:46:in `<main>'
convert.rb:46:in `to_json': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
```

**Comment by dev4dev** [comment]
@umputun с докером там всё ок и с выводом всё ок будет, но вот с кодировкой контента какая-то борода, это ошибка уже при енкодинге в JSON. в общем на сегодня я пока всё, спать пора, сорян

**Comment by tierpod** [comment]
https://github.com/tierpod/convert-idb-xml может, вариант с python будет удобнее (структуру взял из проэкта @dev4dev)

**Comment by umputun** [comment]
две проблемы:

во первых, напрямую присваивать url из комментов работать не будет. Во первых, там enoded спец. символы а во вторых, url скорее все не совпадет с тем, что сейчас.

во вторых:

```
Traceback (most recent call last):
  File "/app/convert.py", line 60, in <module>
    main()
  File "/app/convert.py", line 55, in main
    data = parse_xml(args.INPUT)
  File "/app/convert.py", line 22, in parse_xml
    root = objectify.fromstring(xml)
  File "src/lxml/objectify.pyx", line 1801, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 428
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xD0 0x2E 0x2E 0x2E, line 428, column 25
```

строка 428 (и пара следующих( выглядит так:

```
<text><![CDATA[<a href="http://www.habrahabr.ru/blog/design/24197.html" target="_blank">Концептуальный телефон Brix....</a>
  
<blockquote>Есть на просторах Сети сайтик <a href="http://www.yankodesign.com/" target="_blank">Yanko Design</a>, на котором ежедневно публикуются изыски технической и дизайнерской мысли. По большей части, к полезным или революционным представленные там гаджеты и дизайн-макеты отнести сложно. Так, штучное развлечение креаторов от IT или около того. Но телефон Brix, разработанный дизайнером Секвон Хонг (Seokwon Hong) вполне может стать и коммерческим продуктом.</blockquote>
  
  
&quot;Социальный телефон&quot;? ;)  ]]></text>
```

**Comment by umputun** [comment]
единственный способ найти url это по `<title>` и мэтчить его с сайтом. Для сайта есть API который может помочь https://radio-t.com/api-docs/

**Comment by tierpod** [comment]
По первому вопросу: никак не получается воспроизвести, строку из комментария выше подставил в input.xml и всё прошло успешно. Я понимаю, что проблема с кодировкой, но в каком именно месте... Или, может, гитхаб в quote какие-нибудь символы уже вырезает.

По второму вопросу: в исходном xml файле комментарии только к подкастам? Если так, то можно из
```
<title>Темы для #50</title>
```
достать номер подкаста и потом спросить
```
GET /podcast/50
```
и использовать url из ответа?

**Comment by umputun** [comment]
> По первому вопросу: никак не получается воспроизвести, 

я попробую очистить input от всей персональной информации и выложить. 

>  в исходном xml файле комментарии только к подкастам? 

нет, комментарии ко всем постам. В приведенном в тикет снипете `http%3A%2F%2Fradio-t.com%2Ftemi_dlja_vipuskov%2Ftemyi-dlya-50%2F`

Я предлагаю взать с 50 по 239 (это все, что есть в коментах) по site api и мэтчить по `title`

**Comment by umputun** [comment]
@tierpod @dev4dev добавил в тикет полный инпут файл.

**Comment by udex** [comment]
Первый раз xml вообще руками трогаю, так что, вероятно, в коде много wtf'ов, в том числе отсутствуют тесты, нейминг странный, но на глаз как бы работает - https://github.com/udex/rtxml
Кстати, пути обломал зубы вот на этом url - https://radio-t.com/p/2018/09/25/prep-/

**Comment by umputun** [comment]
@dev4dev по title nичего нельзя найти но по нему можно матчить на совапдения из простыни

**Comment by tierpod** [comment]
Но https://radio-t.com/site-api/last/1000 выдаёт результат только для подкастов Радио-Т:
```
{"title":"Радио–Т 104"}
{"title":"Радио-Т 103"}
```
а в xml файле сильно больше титлов:
```
Темы для ...
Запись и трансляция ...
... и всякого рода нотификации ..
```
Получается, что актуальный url мы можем подставить только для комментариев к темам Радио-Т? Остальное игнорировать (оставить пустым)?

**Comment by umputun** [comment]
не понял, почему только для комментариев к темам. А как по поводу коментариев к самим подкастам, что-то мешает?

**Comment by tierpod** [comment]
Да, теперь понятнее, прощу прощения за невнимательность.

**Comment by umputun** [comment]
@udex на наборе данных что я добавил к тикету оно ничего не возвращает:

 ```
cat ./IntenseDebate.xml | ./rtxml
[]%
```

**Comment by udex** [comment]
@umputun Да, прикрепленный файл оказался, так скажем, с нюансами, парсер xml ломается, например, на предположении, что guid содежит int и еще по мелочам. Главное, что у меня проблемы с определением url (для подкастов и тем к ним, по крайне мере) не возникло, пытаюсь починить.

**Comment by tierpod** [comment]
так же обновил свой репозиторий https://github.com/tierpod/convert-idb-xml

**Comment by udex** [comment]
Пришлось гвоздями в код заколачивать несколько ссылок, также убрал http запросы, просто скачал все из категорий prep и podcast, в итоге вышло довольно страшно, так что опубликую, если необходимо, а пока вот получившийся json - https://github.com/udex/rtxml/raw/master/data/rt.zip

**Comment by tierpod** [comment]
Похож на список title, которые у меня не заматчились.

**Comment by udex** [comment]
Обновленная версия конвертера (just FYI) https://github.com/udex/rtxml

**Comment by tierpod** [comment]
Убрал json https://github.com/tierpod/convert-idb-xml/blob/master/output.txt

**Comment by umputun** [comment]
@tierpod `'pid': 'idb_0'` для тех коментов, у которых нет parent - это неправильно. Такие коменты будут пониматься как дочерние (ответы) на несуществующий родительский коммент. Надо им пустой pid оставить, т.е. `""`

**Comment by umputun** [comment]
одинарные кавычки для всего в json это вообще валидно? мой парсер на попытку импорта на них ругается

**Comment by tierpod** [comment]
Заменил "idb_0" с "", с output.txt это я затупил, просто делал print на dict, а не json. Тоже починил.

**Comment by umputun** [comment]
@tierpod ox, теперь у тебя score это строка. В спеке она int и ожидается там int

**Comment by umputun** [comment]
>  Я их в один пост объединил. Так оставить или вторые выкинуть?

так оставить

>  Еще есть посты "Радио-Т 195.2" и "Радио-Т #82++ (интервью)", их к 195 и 82 добавить?

да, будет хорошо добавить

> И нужно ли выкидывать не сматченные посты вообще?

Несматченные это просто шум для remark42 которые все равно никак не покажутся на сайте, так что выкинуть их вполне разумно

**Comment by tierpod** [comment]
Сконвертировал score в int

**Comment by umputun** [comment]
стало почти хорошо, однако записи типа этой `{"id": "idb_75580127", "pid": "idb_75574191", "text": "<p>ну что ты, не стоит благодарности  </p>", "user": {"name": "umputun", "id": "idb_umputun", "picture": "", "admin": false, "ip": ""}, "locator": {"site": "radiot", "url": ""}, "score": 11, "votes": {}, "time": "2010-05-15T18:48:21Z"}` без url отбиваются как инвалидные импортером. Их надо либо вообще убрать, либо (что еще лучше) дать с каким фиктивым url. Предлагаю `https://radio-t.com/old_comments_idb` в виде url. Тогда я смогу создать пост с таким url и они все там будут.

**Comment by tierpod** [comment]
Заменил пустые url на https://radio-t.com/old_comments_idb

**Comment by tierpod** [comment]
Добавил "запись и трансляция..."

**Comment by udex** [comment]
> да, будет хорошо добавить
> 
> >
Добавил. Несматченные посты вернул с указанным url.

**Comment by umputun** [comment]
Спасибо всем участникам, загрузил. Вот такой, например https://radio-t.com/p/2007/09/02/podcast-50/

Если попадется на глаза нечто, что кажется странным с этими старыми комментами то дайте знать

**Comment by umputun** [comment]
коллеги, а вы не натыкались на какой spam индикатор в xml? Когда я заимпортил появились и коменты которые явный спам и, которые, по идее должны бы быть помечены соответственно со стороны IntenseDebate. Если найдете такой флаг/поле то их надо исключить.

**Comment by umputun** [comment]
еще один косяк, но не наш а источника - в исходном xml явно есть дупликаты. Например, если поискать по "по поводу фильтрования спама в корпорации" то найдется 3 экземпляра одного и того-же комента:

```
<comment id='2058971' parentid='0'>
		<isAnon>1</isAnon>
		<name><![CDATA[stevi]]></name>
		<text><![CDATA[Umputun&#039;у: по поводу фильтрования спама в корпорации <a href="http://www.barracudanetworks.com/ ">http://www.barracudanetworks.com/ </a>Сам не пробовал, но говорят, что неплохо. Надо или нет, решать не мне :)  ]]></text>
		<date>2008-05-24 23:28:15</date>
		<gmt>2008-05-24 23:28:15</gmt>
		<score>0</score>
	</comment>

<comment id='13430961' parentid='0'>
		<isAnon>1</isAnon>
		<name><![CDATA[stevi]]></name>
		<text><![CDATA[Umputun&#039;у: по поводу фильтрования спама в корпорации <a href="http://www.barracudanetworks.com/" target="_blank">http://www.barracudanetworks.com/</a>Сам не пробовал, но говорят, что неплохо. Надо или нет, решать не мне :)  ]]></text>
		<date>2008-05-25 09:28:15</date>
		<gmt>2008-05-25 09:28:15</gmt>
		<score>0</score>
	</comment>

</comment>
	<comment id='14345920' parentid='0'>
		<isAnon>1</isAnon>
		<name><![CDATA[stevi]]></name>
		<text><![CDATA[Umputun&#039;у: по поводу фильтрования спама в корпорации <a href="http://www.barracudanetworks.com/" target="_blank">http://www.barracudanetworks.com/</a>Сам не пробовал, но говорят, что неплохо. Надо или нет, решать не мне :)  ]]></text>
		<date>2008-05-25 09:28:15</date>
		<gmt>2008-05-25 09:28:15</gmt>
		<score>0</score>
	</comment>
```

Было бы круто это отфильтровать. Вообще, вопрос какой оставлять он не такой простой, т.к. к его  id могут быть ответы и надо давить дупликаты с учетом этого.

**Comment by tierpod** [comment]
> а вы не натыкались на какой spam индикатор в xml?

я тоже заметил, что есть явно спам сообщения (да элементарно по словам porn или sex можно найти), но никакого флага не вижу

> по поводу фильтрования спама в корпорации

я нашёл 4, но там скорее 2 по 2 - они имеют немного разный текст, в одном есть target="_blank" в ссылке, в другом - нет, и в самой ссылке в одном есть пробел в конце, в другом - нет

```
... <a href="http://www.barracudanetworks.com/ ">...>
... <a href="http://www.barracudanetworks.com/" target="_blank">...
```

> Было бы круто это отфильтровать.

я попытался, около 1500 сообщений отфильтровалось, в каком виде результат подготовить? полный файл output.txt со всеми результатами но без дублей? или только сообщения-дубли?

**Comment by umputun** [comment]
> в каком виде результат подготовить? 

В том-же что и раньше, т.е. конечный файл для импорта, без дублей.

**Comment by tierpod** [comment]
Сделал, всё там же https://github.com/tierpod/convert-idb-xml/blob/master/output.txt

**Comment by tierpod** [comment]
На данный момент получил результат (и запушил), похожий на правду, но в нём фильтруются только единичные комментарии. Там я ещё находил целые цепочки дублированных комментариев (дерево, родительский комментарий плюс его дети), но я пока не соображу как их можно отфильтровать. Получается, что уже нужно строить деревья комментариев целиком и анализировать, в каких из них есть неповторящиеся комментарии а в каких нет.

**Comment by udex** [comment]
Пробежался глазками по xml и заметил, что спам сообщения подчиняются одному паттерну - в них ссылки начинаются  с чего-то похожего на bbcode - [url. Не скажу, что нет спама без этого признака, но с высокой долей вероятности нет хороших сообщений с этим признаком.

**Comment by umputun** [comment]
если ты про целую кучу спама что идет одним потоком, то это я почистил руками при импорте

**Comment by udex** [comment]
@umputun Не только: https://radio-t.com/p/2009/02/17/prep-125/ - тут есть спам с [url... Как видно, есть спам вообще без ссылок.

**Comment by umputun** [comment]
дописал к remark42 режим очистки. он работает в полу-автоматическом режиме взвешивая каждый комент и удаляя то, что с его т.з. похоже на спам. Добится идеального результата за короткий срок не удалось, но впрочем и цели такой не было. Запустил подсчистил, стало лучше.

**Comment by tierpod** [comment]
написал небольшое количество тестов для алгоритма фильтрации, убедился что всё что я подразумевал в фильтрации - отработало как надо

**Comment by umputun** [comment]
я закрою этот тикет. Дупликаты заставим Грея чистить руками ;)
