### ISSUE TITLE
Переадресатор старых URL на новые

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#24]
@grayru справедиво заметил:

> Много лет назад адрес выпуска выглядел как http://radio-t.com/podcasts/radio-t-94/. Сейчас этот адрес выглядит как https://radio-t.com/p/2008/07/13/podcast-94/. А мы не хотим не в 404 все старые ссылки посылать, а переадресовать их правильно?

Я не очень помню как mapping подобного рода делается в nginx но в любом случае понадобится некий файл с чем-то типа ` http://radio-t.com/podcasts/radio-t-94/ -> https://radio-t.com/p/2008/07/13/podcast-94/` Очевидно, что подобное нельзя сделать никакими магическими regexp но надо информацию про сайт. 

_См #23 где упомнился API для сайта. Как и в том тикете, цель это не элегантный и красивый скрипт, но конечный файл._

**Comment by tierpod** [comment]
Что-то типа этого подойдёт? https://github.com/tierpod/convert-idb-xml/blob/master/urls_mapping.txt

**Comment by udex** [comment]
То же самое сделал для тем для выпусков, если я правильно понял шаблон, по которому они на старом сайте располагались - https://github.com/udex/rtxml/blob/master/data/redirect.txt
Пропуски означают, что на новом этих тем нет (баг?).

**Comment by umputun** [comment]
я вовсе не уверен, что формат со стрелочкой это нечто реальное. Я его привел в виде "некий файл с чем-то типа ...". 

UPD: Если посмотреть [на это](https://www.tendenci.com/help-files/nginx-redirect-maps/) то станет понятно, что там поддерживается вто такое:

```
map $request_uri $new_uri { 
    default ""; 
    /rss/feed/ /rss/; 
    /2011/01/my-article/ /my-article/;
    /staff/ /team/; 
}
```
