### ISSUE TITLE
Слетели стили кода и подсветка синтаксиса

### ISSUE THREAD

**Issue by webkonstantin** [radio-t/radio-t-site#248]
было
![image](https://user-images.githubusercontent.com/2104054/120786488-f092f200-c536-11eb-8e8b-09ef7519e265.png)

стало
![image](https://user-images.githubusercontent.com/2104054/120786415-dc4ef500-c536-11eb-851d-2cf723913320.png)

**Comment by akellbl4** [comment]
Думаю пропустил когда добавлял purge так как классы добавляются после сборки. Добавлю в исключения
