### ISSUE TITLE
Продолжительность выпуска в описании в RSS

### ISSUE THREAD

**Issue by rakleed** [radio-t/radio-t-site#254]
Пожалуйста, указывайте продолжительность выпуска в описании в RSS. Так как сейчас нужно начать воспроизведение эпизода, чтобы узнать его продолжительность, что не всегда удобно.

@q210 https://github.com/radio-t/radio-t-site/pull/226#issuecomment-821868939

**Comment by umputun** [comment]
я не совсем понимаю, зачем это надо и ни один из подкастов, на которые я подписан, такого не делает. 

но если кто возьмется и добавит, то я не против

**Comment by rakleed** [comment]
@umputun почему просто закрыли issue?

**Comment by umputun** [comment]
с 2021 года за это никто не взялся. видимо им, как и мне, непонятно зачем такое надо. Потому и закрыл
