### ISSUE TITLE
Осовременнить дизайн?

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#26]
То, что у нас сейчас (в визуальном смысле) было мной творчески адаптированно много лет назад из какой-то темы WP и потом перехало на octopress и hugo. Функционально вроде все в порядке, и все, что я планировал там показывать, показывается. Однако, возможно пришло время обновить дизайн? Лично я не уверен, что такая необходимость действительно есть, но мои вкусы они минималистичны и, возможно, отстали от модных трендов.

В качестве конечного результата хотелось бы получить PR со всеми изменениями CSS и всего того, что еще надо. Перед тем, как менять утвердите со мной (прямо в этом тикете) мокап, чтоб не тратить время зря.

инструкция для тех, кто не знает как собрать сайт и посмотреть на результат:

- склонировать этот репо: `git clone https://github.com/radio-t/radio-t-site.git`
- [установить hugo](https://gohugo.io/getting-started/installing/)
- `cd radio-t-site/hugo`
- запустить `hugo server` и пойти на url что он скажет

**Comment by isnifer** [comment]
Текущий дизайн хорош и по-прежнему актуален, как мне кажется)

**Comment by Boikolek** [comment]
Никто не будет это делать бесплатно, имхо у всех свои семьи кушать хотят

**Comment by umputun** [comment]
Из того, что наверное надо сделать без всякой связи с изменениями дизайна - автоматическое переключению на темную тему.

**Comment by StaroKep** [comment]
Здравствуйте!
Сделал небольшой набросок и решил показать, что получается.
Выглядеть, как мне кажется, стало свежо (и, может быть, современно).
**Рисовать дальше? Или срезу нет?**
https://drive.google.com/open?id=1y-6TXpRZJi98v_5-jRwxjP6yMp7qZmB1

**Comment by umputun** [comment]
этот дизайн не совсем для того сайта, что есть сейчас. Во первых, у нас нет показа тем. Может это и неплохая идея,  но это точно не вместо последних коментариев. Проигрывателя с временными метками у нас тоже нет. Я не хочу устраивать из этого большой проект и не хочу делать сразу изменения и визуальные и функцниональные, если этого можно избежать.


что касается визуального:

- идея банера "помочь подкасту" так явно и так в середине всего мне активно не нравится. Помощи оно не добавит, но добавит вполне понятного раздражения.
- светло синиие буковки, которых тут большая часть, читаются плохо
-  +/- на плеере вообще непонятно, видимо след./пред. часть но знаки странные и неожиданные.
- все в целом мне не очень понравилось, но возможно какое мелкое изменение где-то и в чем-то может все починить. Мне трудно сказать что именно не так, не совсем моя область экспертизы.

**Comment by sultan99** [comment]
Добавил отсебятины типа чат и всякую всячину, исходил от личных хотелок.

Бывает слушаешь, а там обсуждают какую ту вещь из чата, а вот посмотреть, нет возможности. Предлагалась такая фича как в Youtube, где чат сообщений появляются синхронно с таймлайном. И еще одна хотелка, которую я добавил - разбивка тем, парой хочется пропустить или послушать только конкретную тему.

Глянул предыдущий пост и понял, что не ставится цель делать мега проект 😒 и сбавил обороты.

[Картинку UI](https://ibb.co/M1CzT1t) лучше просматривать в 100%, дабы не размазывались пиксели :)

**Comment by sultan99** [comment]
Забыл, упомянуть. Я взял наглость подменить логотип, текущий логотип никак не вписывался дизайн.
Эскизный логотип, вовсе не замена, мне нужно было, что то туда зарисовать, что более менее подходило по дизайну.

Примечательная фишка, фон можно менять рандомно, чтобы не надоедало, вот возможные варианты:
[природа](https://ibb.co/ZKx1Dzp)
[какая абстрактная фигня](https://ibb.co/qykWn9C)

**Comment by umputun** [comment]
К этому дизайну у меня есть конецптуальное возражение - это все оптимизированно для прослушивания подкаста с сайта. Подобный use-case это относительная экзотика для подкастов вообще и для нашего в частности. Я понимаю, что есть ненулевое количество слушателей которые делают именно так, но большинство слушает это подкаст проигрывателями и превращать сайт в такой проигрыватель я не вижу смысла.

Сайт должен быть удобен для большинства. Оно, я так подозреваю, заходит на сайт чтоб посмотреть темы, предложить свои и поучаствовать (или почитать) коменты. И еще оно заходит чтоб найти ссылку/кнопку на подписку.

Ну и кроме того, этот дизайн противоречит моему тезису выше - т.е. тут я хотел бы реалистичный дизайн на основе той информации, что есть сейчас, а не хотелки как бы оно вообще могло бы быть. По сути если из html и css (или какого sass) этого сделать нельзя вокруг нашего текущего сайта, то скорее всего это вне пределах поставленной задачи. Конечно возможны ислкючения с дополнительным JS по необходимости, но это именно исключения а не полностью новое все.

**Comment by umputun** [comment]
@igoradamenko @Reeywhaar Коллеги, если это просто прикрутить магию для переключения в темную тему автоматически (в сафари) и, возможно, какой иконкой для тех, кто этого не понимают - было бы круто. Это я по поводу https://github.com/radio-t/radio-t-site/issues/26#issuecomment-449592230

**Comment by StaroKep** [comment]
@umputun, здравствуйте!
[Как вам такой вариант?](http://some-space.ru/radio-t.com/)

**Comment by umputun** [comment]
лучше, да. Однако в появившемся блоке про онлайн вещание не хватает главного - ссылки (конпки/иконки) как собственно слушать. Кроме того, на сайте есть банер DO тут непонятно где он будет

**Comment by StaroKep** [comment]
@umputun 
Вариант, над которым я думал:
- у нас есть обратный отсчет. Вот когда он закончится, появится ссылка "Слушать". При нажатии, на которую, произойдет воспроизведение online вещания или нас кинет по этому адресу [http://stream.radio-t.com](http://stream.radio-t.com)

Не понял. **Какой банер DigitalOcean?**

**Comment by Khilkov** [comment]
Всем привет!

К сожалению, совсем CSS`ом обойтись вряд ли получится, но старался минимально модифицировать.

По факту, сейчас есть 2 типа постов: 
1. Сбор тем на следующий выпуск
2. Пост с содержанием выпуска

Предлагаю делать их различного вида, хоть это и, вероятно, усложнит редизайн.
- Светлая тема — https://sketch.cloud/s/ovDYD/kar0k5g/play
- Тёмная сторона силы — https://sketch.cloud/s/ovDYD/oY1Rp5Y/play

**Comment by umputun** [comment]
@StaroKep да, там должен быть банер, который сломался. @grayru обещал починить

**Comment by umputun** [comment]
@Khilkov любопытно, да. Есть некоторые вопросы:

1. Непонятно как будет выглядить post ([типа этого](https://radio-t.com/p/2018/12/22/podcast-629/)) и как будет выглядить page ([типа этой](https://radio-t.com/info/))
1. Непонятно как будет выглядить [страница архивов](https://radio-t.com/archives/)
1. Видимо тут все картинки должны быть квадратными? Как быть со всеми что есть уже?
1. Что с местом для банера DO (см. выше)?
1. Темы визуально выглядят больше чем выпуск, хотелось бы наооборот
1. Непонятно как сделать метки времени на стороне hugo, но наверное можно как-то.
1. Поток последних комментариев, который лично мне кажется весьма и весьма полезным, пропал
1. Twitter виджет, полезность которого весьма условная, тоже пропал
1. Player, который поверх картинки - видимо он должен быть частично прозрачным
1. интересно, как это будет выглядить в темной и светлой теме с коментами. Там кастомизация ограничена цветом фона. Хотя, наверное @igoradamenko сможет помочь если очень надо будет их как-то особо адаптировать.

**Comment by Khilkov** [comment]
@umputun, 

1. На этот и следующий вопрос пока не готовил макеты. Планировал вначале согласовать общую дизайн-концепцию на примере главной страницы, а потом уже перейти к внутренним.

2. ↑

3. Здесь может быть несколько вариантов.

   3.1. В макетах я использовал картинки, что используются и сейчас. Единственное, я находил их в более высоком качестве, (те что сейчас на сайте — мелковаты). Они могут делаться квадратными при помощи обычного CSS:

   `background-size: cover`

   3.2. Можно брать те картинки что юзаются сейчас и вставлять их в центре блока. Тогда не понадобиться искать их в высоком разрешении (или их аналоги)
![image](https://user-images.githubusercontent.com/46132242/50426115-f03a9b00-0896-11e9-9e42-cf070a18a941.png)

   3.3. Доработанный второй вариант. Это когда на фоне дублируется картинка, но она размыта и полупрозрачная.
![image](https://user-images.githubusercontent.com/46132242/50426117-fe88b700-0896-11e9-8e5c-bc03952a7635.png)

   3.4. Комбинировать первый и второй варианты. Для новых постов загружать изображения с высоким разрешением и учитывать, что они будут обрезаться под квадрат. А для старых — использовать вариант номер два.

4. Размеры баннера, если я правильно понял, 240×400, верно? Есть ли какие-нибудь требования по его размещению? Например, он должен быть на первом экране, или можно внизу / в центре разместить? Можно ли будет его сделать не вертикальным а горизонтальным, на всю ширину страницы?

5. Речь о слове «Темы» и числе рядом? 
![image](https://user-images.githubusercontent.com/46132242/50426107-bec1cf80-0896-11e9-9c46-bdfad71cbca3.png)
Если да, то это поправимо :) 
Например, вот так, но возможны и другие варианты.
![image](https://user-images.githubusercontent.com/46132242/50426110-cc775500-0896-11e9-9f92-34730961062d.png)
Если речь о чем-то другом, уточните, плиз.

6. Эх... да, я знаю. Здесь, как и с разными типами постов, я «вылез» за условия задачи. Но когда временные метки отбиваются от топика — и то и другое лучше «считывается». Хочется верить что так можно сделать. Если нет — будем оставлять как было.

7. Этот и следующий вопрос — мой косяк. Не увидел особого смысла в комментариях без привязки к теме обсуждения. Но, скорее всего, это моя личная бага и комментарии с твиттером нужно вернуть. Есть вариант сделать их колонкой справа, как [здесь](https://tjournal.ru). Единственное, на мой взгляд, у блока по ссылке не хватает возможности его свернуть или развернуть, для тех кому он не интересен.
   Внутри блока предлагаю сделать 2 таба. Первый (открытый по умолчанию) — комментарии, второй — твиты.

8. ↑

9. Легко :)

10. Речь о комментариях не на индексной, а внутри поста? Там да, вставляется iframe. Можно, конечно, и в темной теме делать на белом фоне, но смотреться оно будет как бельмо на глазу. Было бы круто перекрашивать и фон и текст, если возможно.

**Comment by umputun** [comment]
- про картинки понял, это нормально, вариант 3.4 вполне разумный. Старые, конечно перезаливать не будем, а новые можно делать больше в момент публикации (на моей стороне).

- про последние коменты колонкой справа - о таком я не думал, но наверное их можно "выползать" справа по клику на что-то, а не все время показывать. Типа как в коментах выползает правая колонка при нажатии на имя. Не уверен как оно в твой дизайн вписывается, но это детали которые ты придумаешь ;)

- Про коменты внутри поста,  я вот что имел ввиду: сейчас на radio-t.com видно как выглядят светлые коменты, на пиратах - как темные. На [news](https://news.radio-t.com/post/temy-slushatelei-629) – оба варианта. 

- по поводу меток времени и hugo – наверное когда мы поймен, что именно надо строить то это можно будет прикрутить либо в момент построения нового поста, либо на в момент генерации hugo

- про банер - призываю @grayru 

- кстати, иконки справа, где загрузить файл и смотреть чат мне как-то не так выглядят, как-то они выбываются из общей картины

**Comment by StaroKep** [comment]
@umputun учел ссылку во время вещания и баннер DO
[Вариант с обратный отсчетом](http://some-space.ru/radio-t.com/)
[Вариант блока во время вещания](http://some-space.ru/radio-t.com/Вещаем)

@Khilkov Очень крутая работа! Сразу видна рука мастера!

**Comment by Khilkov** [comment]
@umputun, Внес правки, обновил макеты.

1. [Главная](https://sketch.cloud/s/ovDYD/wLwlOD9/play)
2. [Главная с открытым чатом](https://sketch.cloud/s/ovDYD/qe9OZve/play)
3. [Главная в темном исполнении](https://sketch.cloud/s/ovDYD/7y5K39p/play)
4. [Чат в темной теме](https://sketch.cloud/s/ovDYD/L0P73x4/play)

Прототип частично кликабельный. Пока что можно только переключать темы (иконка около поиска) и открывать комменты.

@StaroKep, спасибо за теплые слова! Возможно, вы правы и такие радикальные изменения ни к чему. Более того, судя по опросу в Твиттере, аудитории не особо важно будет ли редизайн в принципе ))) 

Предлагаю в этом вопросе положиться на авторитетное мнение ведущих.

**Comment by grayru** [comment]
По баннеру — в упор не понимаю, что там сломалось :). Но там древний флеш, может, его уже браузеры показывать отказываются.
Я еще повожусь, но пока предлагаю не считать это блокером или проблемой. На самом деле, если вы просто предусмотрите большую плашку для генерального спонсора с указанием промокода, я думаю, будет даже лучше.

**Comment by Khilkov** [comment]
@umputun @grayru 
Ссылки поломались. 
Вот правильная — https://sketch.cloud/s/ovDYD/DP0xgnn/play

**Comment by Khilkov** [comment]
@Reeywhaar 
> А чего никто не показывает мокап для мобильной версии?

Хочется вначале согласовать десктопную версию, а уже потом переходить к адаптивам.

**Comment by Reeywhaar** [comment]
Мне кажется надо отметить, что контент каждого поста это маркдаун, и чтобы сделать, например, такую штуку 
![screen shot 2018-12-26 at 20 19 46](https://user-images.githubusercontent.com/884649/50452539-9f38ae80-094b-11e9-92e6-1c7d71bfaadf.png)
Придется либо переписывать уже имеющиеся посты, либо делать какой-то двойной парсинг: markdown -> html -> html, либо писать кастомный маркдаун парсер.

@umputun ты писал 

> Непонятно как сделать метки времени на стороне hugo, но наверное можно как-то

Но правда, как это можно сделать малыми средствами? Мне кажется это важно понять, пока на берегу, а то люди рисуют тут, стараются. В hugo есть [shortcode](https://gohugo.io/content-management/shortcodes/) но тогда придется переписать каждый пост в вид типа 
```
{{% title-image "https://radio-t.com/images/radio-t/rt516.jpg" %}}

{{% topic "Что было на Google Pixel" "https://techcrunch.com/2016/10/04/everything-you-need-to-know-from-googles-pixel-event/" "00:06:19" %}}
{{% topic "Google хочет быть всеми сразу" "http://nymag.com/selectall/2016/10/google-doesnt-want-to-be-apple-it-wants-to-be-everyone.html" "00:21:16" %}}
{{% topic "Новый Samsung Galaxy Note7 тоже хорошо горит" "http://mashable.com/2016/10/05/samsung-galaxy-note7-plane-evacuation/" "00:52:58" %}}

{{% sponsor "https://www.digitalocean.com" %}}
{{% chat-log "http://chat.radio-t.com/logs/radio-t-516.html" %}}
{{% audio "http://cdn.radio-t.com/rt_podcast516.mp3" %}}
```
вместо голого маркдауна. Второй путь, это превратить сайт в spa, брать контент из api, парсить и рендерить сайт джаваскриптом, тут и hugo не нужен. Но представляю каким адским будет парсинг учитывая багаж подкаста, да и вообще это уже прямо проект.

**Comment by umputun** [comment]
@Reeywhaar ну я не зря сказал "непонятно как" :) Контент старых менять кончено не хочется и адаптировать маркдаун по дизайн это тоже не наш путь. Все, что можно легко поменять для новых постов - это перенести метки времени до текста в макрдауне. Т.к. они сейчас "помечены" иитлаиком, то видимо можно эти метки стилизовать через css.

**Comment by umputun** [comment]
> И надо доработать верстку этой панели — там неясно, что комментарии к разным темам.

@grayru - это не про верстку. Лента последних коментариев это ограничение api который знает про комент только ссылку на пост, но не заголовок поста. Кроме того, это виджет который отдает remark42. Его, в принципе, можно стилизовать (это не iframe) но пока там просто нет такого, что ты хочешь.

**Comment by Reeywhaar** [comment]
> стилизовать через css

В принципе да, попробовал через `position:absolute;` но для тем где нет таймстампов, выглядит конфузно [screenshot_2018-12-26 -](https://user-images.githubusercontent.com/884649/50454104-576b5480-0956-11e9-892a-0d118bba3640.png)

**Comment by Khilkov** [comment]
Что-то я запутался ))) «Пилим» дальше или я слишком радикально замахнулся?

**Comment by StaroKep** [comment]
@umputun Да. И мне продолжать дорабатывать или не то?

**Comment by umputun** [comment]
@Reeywhaar может какая особая магия css для этого, типа если есть ts или нет. или какой js чтоб помочь статике?

@Khilkov не вижу причин останавливаться. Однако мобильная версия она важна, не меньше половины с телефонов. 

У нас пока такие известные (мне) проблемы с интеграцией этой темы:

- стилизовать гиттер чат так просто не получится. В принципе, можно через их api свой нарисовать, однако это отдельный подпроект который потребует и бэк и фронтенда. Т.е. пока надо расчитывать на то, что есть сейчас
- с timestamps смотри выше. Надо быть готовым к тому, что TS есть не у всех постов.
- темная/светлая тема ремарка - мне непонятно как оно будет вписываться. Тоже надо быть готовым что прийдется использовать то, что есть сейчас.
- самое важное: когда мне помогали делать дизайн ukeeper то оказалось, что тот кто дизайн рисует, это не тот, кто может его воплотить в css. Я не знаю как у тебя с этим, но если тоже так то понадобятся помощнки которые это приложат к сайту.

@Reeywhaar  - я что-то упускаю?

@StaroKep -  твой вариант он с другой стороны спектра, т.е. его наверняка можно сделать. Мне он кажется вполне логичным минимальным улучшением, однако что-то не так на мой вкус. Как то слишком все для меня малоконтрастно и ярко одновременно. Его можно допилить до степепни удовлетворения, так что предлагаю относться как к плану Б. Думаю, ты согласишся, что если получиться сделать вариант @Khilkov, то будет очень круто.

**Comment by StaroKep** [comment]
@umputun Согласен. Будет очень круто.

**Comment by Khilkov** [comment]
@umputun, По мобильной версии обязательно продумаю. Сейчас хотелось бы с десктопом доразобраться, нарисовав все нужные экраны и перейти к адаптивам.

> - с timestamps смотри выше. Надо быть готовым к тому, что TS есть не у всех постов.

Я предусмотрел эту особенность. Уже сейчас в дизайн-макете у пары выпусков нет тайминга. Например, тут:

![image](https://user-images.githubusercontent.com/46132242/50457250-4547e100-096b-11e9-9f47-2eb6daa26817.png)

Судя по тому, что никому не бросилось в глаза — смотрится хорошо :)

> темная/светлая тема ремарка - мне непонятно как оно будет вписываться. 

Ремарка — это комментарии внутри постов? Если да, то я пока планирую заредизайнить вместе со всем остальным, а потом будем смотреть реально ли это. Ок?

> тот кто дизайн рисует, это не тот, кто может его воплотить в css. Я не знаю как у тебя с этим, но если тоже так то понадобятся помощнки которые это приложат к сайту.

Не смотря на то, что я CSS и HTML знаю, было бы лучше если бы вёрсткой занялся кто-то, кто на ней специализируется. Уже года полтора-два ничего серьезного не верстал, поэтому процесс может сильно затянуться и результат рискует быть не самым качественным. К тому же знание js у меня стремится к нулю.

Я стараюсь сильно не усложнять. Вроде @sw-double был готов взяться за вёрстку или у кого-то еще появится свободное время. Но до верстки еще не близко. 

- Нужно дооформить десктоп. 
- Потом мобилки (375×667) 
- и, возможно, планшеты (768×1024).
- Потом подготовить UI Kit как должны выглядеть элементы в различных состояниях 
- и только потом можно верстать.

Если план ок — буду воплощать :)

@Reeywhaar

> В принципе да, попробовал через `position:absolute;` но для тем где нет таймстампов, выглядит конфузно [screenshot_2018-12-26 -](https://user-images.githubusercontent.com/884649/50454104-576b5480-0956-11e9-892a-0d118bba3640.png)

Ваще крутяк! А получится еще временные метки и к сетке привязать, как думаешь? Чтобы они не просто слева были, а занимали ширину одной колонки + межколоночник? Как на скрине ниже.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/46132242/50457233-29443f80-096b-11e9-8f61-9d4e341add72.png">

**Comment by umputun** [comment]
> Ремарка — это комментарии внутри постов?

да, это [remark42](https://remark42.com) который для коментов

> Если план ок — буду воплощать :)

полный вперед!

**Comment by Reeywhaar** [comment]
@umputun по части css магии нет, но вполне можно джаваскриптом модифицировать DOM, переставлять элементы. На дизайне @Khilkov, например, все равно придется что-то делать, чтобы прибить плеер к картинке, надо будет вычленить блок со спонсорами, аудио, и логом. И хотя это теоретически, но если подкаст будет содержать не только список тем, а просто произвольный список, все поломается. Мне подход полагаться на такой *греп* не нравится, но в принципе может работать.

Еще иногда бывают посты которые не подкасты: https://radio-t.com/categories/news/, я думаю их стоит показать в дизайне.

**Вкусовщина:**
* Сейчас стало влезать меньше информации. Комментарии с твиттером убраны в схлопывающийся сайдбар, на который, как мне кажется, просто никто не будет нажимать.
* Навигация разбросана по нескольким местам, хочется одного места, как сайдбар сейчас, где есть все ссылки. Чат в блоке про онлайн вещание, "подкаст на Alexa" похоронен в футере, rss в шапке.

> Ваще крутяк! А получится еще временные метки и к сетке привязать, как думаешь? Чтобы они не просто слева были, а занимали ширину одной колонки + межколоночник? Как на скрине ниже.

Не очень понял, Ты хочешь, чтобы при маленькой ширине экрана, таймстамп разбивался на две строки. Можно, но сложно, через media-queries и max-width, вручную короче. Но мне не кажется что метку можно красиво разбить на две строки вообще. Да и зачем, у неё же не динамическая длина, сразу понятно, что это 8 символов.
Я сейчас сделал таким образом:
```
.entry-content li {
	color: transparent;
	font-size: 0rem;
	margin-left: 4rem;
	position: relative;
}

.entry-content li a {
	font-size: 1rem;
}

.entry-content li em {
	color: #444;
	position: absolute;
	left: -4rem;
	top: 0;
	font-size: 0.8rem;
	font-style: normal;
	opacity: 0.7;
}
```
То есть логика такая:
Уменьшить размер шрифта до 0, чтобы скрыть `-` и `.` у пунтка, потом у ссылок и метки восстановить размер шрифта, сдвинуть пункт на ширину метки, и метку зафорсить налево.

**Comment by grayru** [comment]
> > И надо доработать верстку этой панели — там неясно, что комментарии к разным темам.
> 
> @grayru - это не про верстку. Лента последних коментариев это ограничение api который знает про комент только ссылку на пост, но не заголовок поста. Кроме того, это виджет который отдает remark42. Его, в принципе, можно стилизовать (это не iframe) но пока там просто нет такого, что ты хочешь.

Я вообще ничего не хочу. Но мне показывают сплошную ленту комментариев и это на порядок хуже того, что сейчас есть на сайте, — там есть хоть намек на контекст комментария. В этой ленте нет ни указания на пост, к которому оставлен комментарий, ни даты и времени, так, отрывок чата.

**Comment by grayru** [comment]
А, пардон, это у меня в памяти старые комментарии отложились — в нынешних та же бессмыслица.

**Comment by umputun** [comment]
Нет, это не о тех комментариях. Сплошной поток (последние комменты) есть и сейчас, он слева и в нем непонятно на какой пост это комент (пока не клинешь). Об этом и была часть "ограничение api который знает про комент только ссылку на пост". Те коменты, что к постам - они так и остануться и там все понятно что к чему. Просто этого мокапа мы пока еще не видели.

UPD: про "бессмыслица", ну ок. Мне это никогда не казалось особо важным, однако добавить (сохранить и показать) подобную информацию можно. Для таких пожеланий есть https://github.com/umputun/remark/issues

**Comment by umputun** [comment]
1. В станице "О нас" не надо срывания покровов :) Под кружочками просто ники, не надо имя-фамилия. Если хочется, можно добавить страну
1. Архивы - надеюсь что этo вообще делается как-то через css, @Reeywhaar ?
1. страница топика с коментами по средине выглядит как-то странно. Может просто непривычно, не уверен. А может коменты надо растянуть на всю ширину?
1. Все типы постов хорошо, ожидаемо

**Comment by Khilkov** [comment]
@umputun 
> А может коменты надо растянуть на всю ширину?

Для разрешений меньше 1024 — скорей всего так и сделаем, но при более высоких — строки получатся слишком длинными, неудобно читать.

> В станице "О нас" не надо срывания покровов :) Если хочется, можно добавить страну

Похоже на секрет Полишинеля, но как скажете :)

- ksenks — США
- Bobuk — Россия
- Gray — Украина
- Umputun — США

Верно?

**Comment by umputun** [comment]
по поводу 3 - может на этих страницах "прилепить" раскрытую правую колонку (с потоком коментов), раз все равно место простаивает. но показывать не оверлеем как на индексах, а частью странцицы.

да, страны правильно. только ksenks с большой буквы ;)

**Comment by umputun** [comment]
> Для разрешений меньше 1024 — скорей всего так и сделаем, но при более высоких — строки получатся слишком длинными, неудобно читать.

А все остальное тоже фиксируется по ширине максимальной?

**Comment by Khilkov** [comment]
Правда, могут же возникнуть проблемы со сменой фона у комментариев, они-то ифреймом вроде вставляются... хз.

**Comment by umputun** [comment]
> могут же возникнуть проблемы со сменой фона у комментариев, 

нет, это не проблема, фон там прозрачный и можно "подложить" любой. И да, с серым блоком смотрится лучше.

> Вторая трабла в том, что будут перекосы: контента в посте очень мало (например у постов типа «Темы для выпуска»), а правая колонка с комментами перегружена. Имхо, лучше оставить комменты как сейчас.

Да, согласен

**Comment by umputun** [comment]
@Reeywhaar по поводу "вкусовщины"

> Сейчас стало влезать меньше информации. Комментарии с твиттером убраны в схлопывающийся сайдбар, на который, как мне кажется, просто никто не будет нажимать.

Вообще мне это кажется скорее положительным чем отрицательным. Сейчас информации слишком много. Коментарии нажимать - я буду :) И, теоретически, там можно будет добавить таб для чата, когда (если) будем к этому готовы

> Навигация разбросана по нескольким местам, хочется одного места, как сайдбар сейчас, где есть все ссылки. Чат в блоке про онлайн вещание, "подкаст на Alexa" похоронен в футере, rss в шапке.

Тоже не согласен. Надо решить что главное показать в шапке, а второстепенное вниз. Кроме того, оно может дублироваться и в каком новом верхнем табе типа "Полезное", если надо все собрать.

**Comment by Reeywhaar** [comment]
@umputun по поводу вкусовщины: you're the boss, и возможно, только возможно, во мне говорит брюзга, который просто привык.

По поводу архивов: Саму таблицу сверстать можно, легко если на [css grid](https://caniuse.com/#feat=css-grid), средне если на [flex](https://caniuse.com/#feat=flexbox) и хардмод на float. Плюс надо поработать с hugo шаблонами, матчить категорию, и если подкаст, то вычленять номер, а если не podcast и не prep, то указывать через class, что новость должна занимать две плашки.
Непонятно, как будет выглядеть пост занимающий две плашки, если он будет на 4м, 8м и тд месте, и вообще непонятно живуче ли это для мобильной версии, но выглядит красиво.
![screen shot 2018-12-28 at 06 35 32](https://user-images.githubusercontent.com/884649/50501678-fe411500-0a6a-11e9-9b90-d2ffff9532c6.png)

Не уверен, что такой query можно в hugo запросить, пока не попробуешь, не узнаешь:
![screen shot 2018-12-28 at 06 31 03](https://user-images.githubusercontent.com/884649/50501765-b1117300-0a6b-11e9-84c8-4f29dcc845fe.png)

Вот такие breadcrumbs они не правильные:
![screen shot 2018-12-28 at 07 08 41](https://user-images.githubusercontent.com/884649/50502330-86291e00-0a6f-11e9-918c-3db4e8bca588.png)
Посты не является частью категории, а наоборот, у поста может быть много категорий, и непонятно, как строить такие крошки. Я бы скорее понял крошки вида `главная/2018/12/24/prep-480` как в url, но они не очень полезные и тогда нужны страницы для `главная/2018/12`, `главная/2018/12/24`. Вообще у сайта нет какой-то сложной иерархии, либо page либо post, и я не думаю, что крошки вообще нужны, м?

Подумал для тем слушателей, можно сделать отдельный layout и переместить комментарии в блок контента, как сейчас на https://news.radio-t.com/post/temy-slushatelei-629, грубо
![screen shot 2018-12-28 at 07 18 03](https://user-images.githubusercontent.com/884649/50502530-07cd7b80-0a71-11e9-96c8-6b606c808145.png)

**Comment by Khilkov** [comment]
@umputun, по моим подсчетам это последняя порция страниц для десктопа, вроде как все учел. Если нет — пишите, исправлюсь ))

- [Вещание](https://sketch.cloud/s/ovDYD/l1rvbg4/play)
- [Подписка](https://sketch.cloud/s/ovDYD/karJgP9/play)
- [FAQ](https://sketch.cloud/s/ovDYD/R1d0mvx/play)
- [Реклама](https://sketch.cloud/s/ovDYD/DP0joKq/play)

Если все ок — будем переходить к телефонам.

**Comment by Khilkov** [comment]
@Reeywhaar 
> Непонятно, как будет выглядеть пост занимающий две плашки, если он будет на 4м, 8м и тд месте, и вообще непонятно живуче ли это для мобильной версии

Хороший вопрос. Думаю, если пост, занимающий 2 плашки оказался последним в ряде, то он переносится на новую строку, а его место просто оставляем пустым.

По поводу крошек, да, согласен, в них не особо много смысла при таких раскладах. Заменил везде на «Вернуться на главную», но можем и вообще убрать (на главную можно вернуться стандартно как везде — кликнув по лого).

> Подумал для тем слушателей, можно сделать отдельный layout и переместить комментарии в блок контента

Офигенная идея. Реализовал и макете )))

**Comment by umputun** [comment]
выглядит хорошо, хотя совсем непонятно где и как этому hugo научить. Там сейчас 2 вида - посты и страницы которые генерятся. Все посты и все страницы генерятся одинаково. Наверное (надеюсь) можно в страницах это как-то по разному рендерить, но как именно - тут лично мне совсем непонятно.

**Comment by umputun** [comment]
есть еще такая страница: https://radio-t.com/license/ Вообще, согласно hugo у нас есть вот такие страницы - https://github.com/radio-t/radio-t-site/tree/master/hugo/content/pages

**Comment by Reeywhaar** [comment]
Hugo можно научить, там много способов, например прописав в `/hugo/layouts/pages/single.html`:
```
{{ if eq .File.Path "pages/info.md" }}
  {{ partial "pages/info" . }}
{{ else }}
  {{ .Content }}
}}
```
Соответсвенно, кастомный хтмл будет в `/hugo/layouts/partials/pages/info.html`.
Проблема только в том, что чтобы что-то поправить, надо будет править хтмл в `/hugo/layouts/partials/pages/info.html`, а контент в `/hugo/content/pages/info.md` если и стоит описывать, то только какой-то совсем простой текст, который уже можно вставлять в сложный шаблон, но я думаю это неизбежно если хочется иметь более-менее сложную верстку.

Еще можно прямо в маркдауне`/hugo/content/pages/info.md` писать хтмл.

**Comment by Khilkov** [comment]
@umputun может, имеет смысл попробовать десктопную версию сверстать и прикрутить? Тем самым проверить реализуемо ли все это в принципе, пока не рисовали адаптивы?

**Comment by Reeywhaar** [comment]
btw, я форкнул репо, добавил туда дев докер с webpack/babel/scss и hugo server, чтобы удобно разрабатывать. Плюс немного попытался переписать старый css, потому как он видимо когда-то тоже был сгенерирован из scss и превратился в кашу, которую невозможно поддерживать. Чтобы запустить, надо в терминале написать `docker-compose -f docker-compose.dev.yml up` после чего сайт будет на `http://localhost:9000`

**Comment by Khilkov** [comment]
Прикинул главную страничку для мобильного — https://sketch.cloud/s/bMAo5/eKo78r2/play

**Comment by Khilkov** [comment]
Речь вот про эти кнопки?
![image](https://user-images.githubusercontent.com/46132242/50541339-ae6e6500-0bb4-11e9-900d-d66966c38f93.png)

**Comment by umputun** [comment]
да. В принципем, видя такое слушатель подкаста сразу понимает что это и зачем. Ну и нам можно прятать все остальные виды подписки в какой "Подписаться другим способом" или что-то в этом роде. Например, подписка на архивные выпуски, спотифай и все прочее - это экзотика, для которой достаточно страницы https://radio-t.com/feeds/

**Comment by Khilkov** [comment]
принял.

**Comment by sw-double** [comment]
приступаю ⏱

**Comment by Eugene-Sviridov** [comment]
@sw-double Привет. Как успехи? Могу взять какую-нибудь часть в помощь?

**Comment by umputun** [comment]
непривычно, но вроде нормально.

**Comment by umputun** [comment]
@Khilkov по поводу верстки - ты посматривай краем глаза, что там получается. А то программисты (не эти конкретно, эти молодцы, я про сферических программистов в вакуме) тихо и незаметно так поменяют дизайн, что не потом узнаешь ;)

**Comment by Eugene-Sviridov** [comment]
@Khilkov заметил небольшие отклонения в типографии здесь #27 . Как бы посмотреть все размеры на макете? Не нашёл download на sketch.cloud

**Comment by Khilkov** [comment]
@Eugene-Sviridov скажи, пожалуйста, свое мыло — дам доступ в Фигму. Или вышлю исходник Скетча, как тебе будет удобней?

@umputun Да, я обратил внимание, что есть несоответствия в верстке с изначальным замыслом.  Причем, есть очень крутые, на мой взгляд, идеи (например, новый  проигрыватель с воспроизведением по меткам, или аватарки предложивших темы), а есть места, которые можно будет улучшить эстетически. 

Планирую сегодня-завтра собрать свои комментарии в доку. Единственное, я не всегда понимаю что можно сделать, а что нельзя (или слишком сложно), поэтому буду писать обо всем, а там уже на усмотрение ребят.

**Comment by Eugene-Sviridov** [comment]
@Khilkov eugenesv619@gmail.com. Небольшой вопрос про ховеры на ссылки, сейчас меняется бэкграунд и нижний бордер, оставить как есть или обойтись только text-decoration: underline?

**Comment by Khilkov** [comment]
@Eugene-Sviridov тут чисто вкусовщина. Можно оставить и как есть, но мне больше нравится когда у ссылок если уж и есть подчеркивание, то border-bottom: 1px solid rgba(0,0,0,.15); а на ховер и текст и подчеркивание просто становятся черными.

**Comment by Eugene-Sviridov** [comment]
@Khilkov понял, сделаю 👍

**Comment by umputun** [comment]
и мы переехали, ура! Спасибо всем участникам процесса.

@Khilkov & @sw-double только что заметил, что лого (то, что в углу) не на том языке. Можно его по русски нарисовать?

**Comment by Khilkov** [comment]
Логотип на русском
[logo_rus.svg.zip](https://github.com/radio-t/radio-t-site/files/3181229/logo_rus.svg.zip)
