### ISSUE TITLE
Оценка радиовыпуска пользователями по указанным критериям

### ISSUE THREAD

**Issue by isKUL** [radio-t/radio-t-site#265]
Нужно как то расширить возможность описания каждого радиовыпуска.
Мысль про что - ведущие могут в обычном выпуске умных вещей наговорить (больше чем в гиковском), а в описании к выпуску этого можно не понять. И наоборот, гиковский выпуск не всегда может быть гиковским. Т.е. свойства объекта "выпуск" формируются только после его полного создания ведущими, так сказать.

Как можно решить?
1. Весь звук в субтитры перевести.
2. Как мистер Алексей предлагал, - сделать облако тегов.
3. Можно сделать микро-набор свойств характеризующий выпуск.

Решение:
1. Технически сложно решать, т.к. далее ещё придётся эти субтитры обрабатывать по ключевым словам.
2. Теги делать придётся ведущим или кураторам, опять лишние тягости.
3. Вариант, который я предлагаю всем умным подумать сделать (картинка во вложении)

Технический взгляд на 3 вариант:
1. Добавить до 5 свойств к выпуску которые отражают основные характеристики интересующие слушателей.
2. Голосовать на "лайканье" можно только в течении недели. Т.е. когда вышел выпуск и до момента выхода нового выпуска. Таким образом рейтинг лайков будет более/менее ровный у всех. Кто слушает с запозданием - их проблемы.
3. Во время этой недели можно держать динамическую таблицу по id кукам (ну и по ip бонусом), чтобы более/менее от кликеров защитится. А далее, когда неделя прошла, делать анализ и хранить в истории базы данных только структуру вида интежеров (203, 0, 9999, 0, 0) с запретом лайков.
![Безымянный](https://user-images.githubusercontent.com/58237872/148630949-504a3ca4-5b74-456b-abbd-2f82f8b37d65.png)

**Comment by umputun** [comment]
это описание не отвечает на два важных вопроса:

1. Зачем это все надо? Темы примерно есть, в коментах можно оставить свои впечатления. Зачем эти "типа теги" нужны, чем и кому они помогут? Если для поиска, то нет. Или кто-то увидив 10 за гиковасть и 20 за мудрые истории решит что именно? 
2. Кто будет заниматься реализацией бекенда и фронтенда? 

Теоретически, подобное наверное можно сделать как часть реализации пулов голосования внутри коментов (дописать в remark42, там даже какой-то тикет про что-то такое был), и добавлять и пинить такой комент автоматически в процессе производства подкаста. Однако, мне вся эта идея не понятна в принципе. Нам (ведущим) это вроде-бы совсем не надо, нам и так хорошо. И подозреваю, что слушателям это не надо, и даже если такое кто напишет и каким-то чудом убедит меня PR принять, на эти 👍 👎 будут кликать 2 с половиной человека и то не на каждый выпуск.

П.С. мой пессимизм он из опыта. Слушатели они у нас слушатели, изредка комментаторы. Большего от них ожидать трудно, они не за тем сюда приходят чтоб наполнять нам тэги.

**Comment by isKUL** [comment]
Уважаемый Умпутун, вы немного не недооцениваете, что делаете. Вас слушает население крупного посёлка городского типа. И поскольку контента много и он стабильных, хотелось бы его упорядочивать, выбирать?!

1. Поскольку время - деньги. Или не все могу позволить всё подряд слушать, то хотели бы слушать только например концентрацию гиковости (которая не всегда есть в "гиковские выпуски", но может зашкаливать в обычных выпусках). То возможно хотелось бы, когда есть час/два времени, выбрать именно выпуск гиковский или с интересными поучительными практическими историями мудрецов.
2. Инициативная группа разумеется ;-)

На вопрос слабой инициативности людей:
1. Многие старые/ленивые.
2. Кто то обиженный, что его прошлую тему пропустили или высмеяли, и теперь он забил.
3. Писать комменты социально опасно, могут высмеять публично (кто то потом спать не сможет из-за стресса).
А фанаты, которые идут локомотивом и слушают (даже в онлайне), смогут вполне отлайкать выпуски и помочь тем, кто слушает в записи.

Разумеется может я не прав и всем на всё плевать и ни кто ничего не хочет. Кстати, можно спросить в эфире и чтобы в комментах ответили, остались ли способные нажать ЛКМ (можно кстати каждому юзеру давать не 1 клик, а по клику на каждую категорию (как при оценке на онлайн-кинотеатрах, после просмотра фильмов)), чтобы оценить контент для истории, для потомков?

**Comment by umputun** [comment]
про поселок это ты загнул, скорее средний американский город ;)

Однако, у нас нет цели сохранять время/деньги наших слушателей. Это даже как-то странно слышать на фоне того что и деньги и время тратят именно ведущие. В любом случае, ничего не мешает слушателям описывать степень гиковсти прямо сейчас в коменте, и голосвать за комент типа "тут одна гиковость!", но никто этого не делает и не будет делать.

> и всем на всё плевать и ни кто ничего не хочет

повторю, это сайт подкаста, сюда приходят его слушать. При этом, додавляющее большинство это делает нормальным (для подкастов) образом а не через сайт, и  на сайт заходит примерно 2-3% слушателей. Городить это все для 2% среди которых может найдется десяток тех, кому это надо - затея не очень продуктивная.

**Comment by isKUL** [comment]
ну ... как хотите
в любом случае, Спасибо, за потраченное внимание!
