### ISSUE TITLE
Как запустить сайт?

### ISSUE THREAD

**Issue by arthurgubaidullin** [radio-t/radio-t-site#28]
Запустил `docker-compose run hugo` и оно не запустилось. Что делать?

Вывод консоли:
```
$ docker-compose up
Starting updater             ... done
Recreating radiotsite_hugo_1 ... done
Attaching to updater, radiotsite_hugo_1
hugo_1     |  === generate pages ===
hugo_1     | Error: Unable to locate Config file. Perhaps you need to create a new site.
hugo_1     |        Run `hugo help new` for details.
hugo_1     |
hugo_1     | /srv/exec.sh: line 5: /srv/hugo/generate_rss.py: not found
radiotsite_hugo_1 exited with code 127
```

```
$ docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:
  Version:      18.09.0
  API version:  1.39 (minimum version 1.12)
  Go version:   go1.10.4
  Git commit:   4d60db4
  Built:        Wed Nov  7 00:52:55 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
```
$ docker-compose version
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017```

**Comment by arthurgubaidullin** [comment]
Разобрался.

**Comment by umputun** [comment]
я попробовал строго согласно инструкции, т.е:

```
git clone https://github.com/radio-t/radio-t-site.git
cd radio-t-site
docker-compose run hugo
```

Оно на это построило контейнер (у тебя он построен при другом запуске?) потом все построило без всяких ошибок. Видимо какая-то шиндовая специфика, я не винде не пробовал но на линукс и маке. Может ему `volumes` пути не нравятся в композе (типа - ./hugo:/srv/hugo), не уверен

**Comment by umputun** [comment]
если разобрался и это не локальная проблема - поделись тут, вдруг еще кто на такое попадет.

**Comment by arthurgubaidullin** [comment]
Суть проблемы: директория проекта не маунтилась, поэтому docker не видел файлов.

Решение: директория проекта должна быть в пользовательской директории. В интернетах пишут, что можно обойти как-то, но я уже боюсь трогать. (:

P.S. У меня Docker Toolbox & Windows 10.

**Comment by arthurgubaidullin** [comment]
Вот теперь другой вопрос: сайт сгенерирован, а чего веб сервер не поднимает оно? Не должно? Как быть?

**Comment by umputun** [comment]
это генератор статики, он не должен никаких серверов поднимать. Результат его работы то, что оно в public положило.

Но если очень хочется, то можно:
1. добавь в композ мэпинг `8080:8080`
1. запусти `docker-compose run hugo sh -c "cd /srv/hugo && hugo server -p 8080"`

**Comment by arthurgubaidullin** [comment]
К сожалению, запустить веб-сервер в докер-контейнере через `hugo server` не получилось.

Я пробовал через команду: `docker-compose run --rm -p 8080:8080 hugo sh -c "cd /srv/hugo && hugo server -p 8080 -b 0.0.0.0"`

А так заработало: `docker-compose run --rm -p 8080:8080 hugo sh -c "cd /srv/hugo/public && python3 -m http.server --cgi 8080"`.

P. S. Ещё есть промежуточный этап "1.1" — прописать порты в VirtualBox для NAT.
