### ISSUE TITLE
Проблема с  белой темой. 

### ISSUE THREAD

**Issue by semen-trololo** [radio-t/radio-t-site#336]
Какая то  проблема с отображением темы при переключение без обновления страницы. 
![2023-07-05_15-57-56](https://github.com/radio-t/radio-t-site/assets/95562395/9d57726f-04a9-4528-8346-3813dbf8157e)
![2023-07-05_15-58-51](https://github.com/radio-t/radio-t-site/assets/95562395/b77a5a57-edcb-4c14-9a99-628032ea429d)
![2023-07-05_16-06-48](https://github.com/radio-t/radio-t-site/assets/95562395/d6795908-6d87-4690-bb38-1166dbec835a)
![2023-07-05_16-07-14](https://github.com/radio-t/radio-t-site/assets/95562395/6a05d433-39ff-4002-b43a-d8c3627f2853)

**Comment by shvl** [comment]
@webkonstantin кажется, это дубль https://github.com/radio-t/radio-t-site/issues/323
