### ISSUE TITLE
Нет возможности регулировать громкость воспроизведения.

### ISSUE THREAD

**Issue by stickandstone** [radio-t/radio-t-site#48]
В последнем редизайне исчезла крутилка громкости в компоненте воспроизведения подкаста. Теперь чтобы сделать тише нужно менять громкость самой ОС или физически крутить ручку. Верните взад, пожалуйста. Спасибо.

**Comment by umputun** [comment]
re #26

**Comment by umputun** [comment]
@sw-double такое можно добавить в player? Десйтвительно, раньше такое было и хотя я в этом ползунке не вижу особого смысла, некоторым такое, видимо, надо.
