### ISSUE TITLE
Перевести comments 

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#50]
<img width="483" alt="k9mm4-201905-14212936-wo8h9" src="https://user-images.githubusercontent.com/535880/57744590-73665d00-768f-11e9-80b6-739497f92293.png">

Вместо этого хотелось бы видеть слово "комментарии"  @Reeywhaar - это вообще делается со стороны @sw-double или оно у нас там крепко прибито в ремарке?

**Comment by Reeywhaar** [comment]
Ремарк возвращает только число. Остальное в компоненте https://github.com/radio-t/radio-t-site/blob/a2593890ffc3075eb5351753104244cf1b3a888d/hugo/layouts/partials/comments-counter.html#L4

Кстати хорошо бы было вместе с декларативным апи, когда мы просто грузим скрипт, и он автоматически вставляет число в `<span class="remark42__counter" data-url="https://url">`, дать возможность явно спрашивать ремарк. У нас сейчас есть объект `window.REMARK42`, мы его используем для смены темы: `window.REMARK42.changeTheme('light');`. Можно добавить туда `window.REMARK42.getCommentsCount('https://remarkhost', 'site-id', 'https://url')`. При получении числа уже можно подставить "комментарий" с нужным падежом.

Либо если продолжать декларативое апи, то можно сделать чтобы ремарк при вставке диспатчил `RemarkCommentsCountInsert` event, а там можно было бы перед загрузкой ремарка делать `element.addEventListener('RemarkCommentsCountInsert', (count, url) => {somenthingWithCount(count);})`

**Comment by umputun** [comment]
>  Остальное в компоненте

это я не очень понял. Т.е. "comments" это то, что генерится на стороне hugo ? Если так, то можно пока обойтись дешево и не возится с окончаниями выводя слово "коммент.", т.е. "15 коммент."

**Comment by Reeywhaar** [comment]
> Т.е. "comments" это то, что генерится на стороне hugo ?

Да

**Comment by umputun** [comment]
круто, даже с падежами!
