### ISSUE TITLE
новый favicon в сафари выглядит странно на сером фоне

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#51]
<img width="351" alt="hxnrz_20190515_001554 q8ub5" src="https://user-images.githubusercontent.com/535880/57750160-bb44ae80-76a6-11e9-866b-504db0ea89d2.png">

**Comment by umputun** [comment]
результат #26

**Comment by Khilkov** [comment]
Да, что-то не очень смотрится на сером фоне. Можем попробовать сделать цвет фавиконки темней, должно стать лучше.
[favicon_package.zip](https://github.com/radio-t/radio-t-site/files/3181267/favicon_package.zip)
В архиве переделанные иконки и инструкция по подключению.

**Comment by umputun** [comment]
<img width="509" alt="m3szb-201905-19121006-p1jw7" src="https://user-images.githubusercontent.com/535880/57985552-18d25580-7a2f-11e9-91c7-f3c2fdfcf04c.png">

Стало лучше, но все равно прошлая смотрелась лучше. Может ее вернуть ?

**Comment by eshill** [comment]
Дело хозяйское, но преемственности не будет, между лого и фавиконкой (((
А что не нравится в текущей версии, может смогу поправить?

**Comment by umputun** [comment]
не, я не навязываю художнику :) Мне она кажется "грязной",  в том смысле что ее белыы (серый) внутри выглядит так, что хочется протереть монитор. Может просто эти две палочки в середине сделать более белыми?
