### ISSUE TITLE
Проблема с версткой на экранах шириной 320px

### ISSUE THREAD

**Issue by mezhevikin** [radio-t/radio-t-site#52]
![Image of Yaktocat](https://dl3.pushbulletusercontent.com/UMeBjR7j3PzfAPhB8wCKl2X61KFDJP6M/IMG_2968.PNG)

iphone 5s. iOS 10. Mobile Safari

**Comment by umputun** [comment]
@sw-double эта починка поломала на на iphone X которыч с большим экраном
<img width="484" alt="gd0hf-201905-15143300-3ja5y" src="https://user-images.githubusercontent.com/535880/57803567-59c02680-771e-11e9-896e-af4bf9a6a5d4.png">

**Comment by umputun** [comment]
@mezhevikin подтверди pls, что стало хорошо.

**Comment by mezhevikin** [comment]
@umputun подтверждаю. стало хорошо 👍
