### ISSUE TITLE
Дублирование запросов на количество комментариев

### ISSUE THREAD

**Issue by DeWenS** [radio-t/radio-t-site#53]
[Video](https://monosnap.com/file/XaKovY1t5XOuoJux8e3kO86PdkpN8F)

<img width="1137" alt="_048- 40AB 2019-05-15 16-54-58" src="https://user-images.githubusercontent.com/1389322/57781189-60f12f80-7732-11e9-8022-027516571741.png">

**Comment by umputun** [comment]
re: #26

**Comment by umputun** [comment]
пинг @sw-double

**Comment by sw-double** [comment]
это fixed
