### ISSUE TITLE
Отладочные логи (счетчика?) на https://radio-t.com

### ISSUE THREAD

**Issue by vblz** [radio-t/radio-t-site#56]
Каждую секунду в логи выводится, видимо, отладочная информация, судя по всему, показывает html-элемент со счетчиком до начала эфира. Нужны ли это логи на продакшн-окружении?
![изображение](https://user-images.githubusercontent.com/2076171/57798233-beeb3a80-7765-11e9-86e0-9b77547f4d4e.png)

**Comment by sw-double** [comment]
fixed
