### ISSUE TITLE
обновление списка свежих комментариев в бэкграудне?

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#60]
Возможно я ошибаюсь, но судя по логам новый сайт делает `/api/v1/last/30?site=radiot` в фоне? Если это так, то не надо этого, достаточно в момент загрузки стрницы это сделать один раз. 

cc: @sw-double

**Comment by sw-double** [comment]
идея в том, что после загрузки страницы переход по сайту уже осуществляется без полной перезагрузки, то есть если слушаешь подкаст, например, то два часа комментарии обновляться не будут

поэтому прикрутил периодическое обновление

обновление работает только если текущая вкладка активна, и выключается если неактивна или свернута

я не раз ловил комментарии в реальном времени, хотелось бы такую возможность оставить

**Comment by umputun** [comment]
Такое поведение фронтенда мне кажется неожиданным, неконситентным и плохо поддерживаемым на сторне бэкенда. 

Неожиданность и неконсистентность относится к тому, что большая часть обновлений комментариев статична, а этот кусок вдруг динамичен. Скорее всего, если сайд бар обновился и пользователь пытается из списка последних перейти на комент который не загружен на странице, то получится не то, что ожидалось.

Сервер и API не готовы к такому use-case. Технически, много запросов на /last проблем не вызывают, т.к. они кешированы на стороне сервера, однако этот запрос не предназначен для подобых "живых обновлений". Если бы у нас был такой запрос, он бы был либо websocket какой либо комет. Сейчас, по сути, клиент гоняет без особого смысла список из 30 коментов в фоне. Ну и по мелочи, т.к. /last это "обычный" запрос (с т.з. бэкенда) к нему и отношение как к обычному, а не повторяющемуся, например он логируется. В принципе, можно себе представить новый API метод, типа "/api/v1/last/30?site=radiot&after=time", который подходил бы для этой роли лучше. Ему можно бы и добавить параметер для ожидания (wait=60s) чтоб он придерживал ответ если нет ничего нового. Однако, подобный API будет смотрется странно на сторне remark42 бэкенда, который пока не берет на себя подобные динамические обновления во всех прочих местах.

Исходя из этого всего я и предложил избавится от динамики. Я не уверен как решить " после загрузки страницы переход по сайту уже осуществляется без полной перезагрузки". Видимо, если отркывается список последних по нажатию кнопки, то в этом момент можно попросить список. Что касаетется открытого на широких экранах, то я без понятия, но наверное можно что придумать?

**Comment by umputun** [comment]
> Что касаетется открытого на широких экранах, то я без понятия, но наверное можно что придумать?

вот тут https://github.com/umputun/remark/issues/329#issuecomment-493213325 была высказана любопытная идея добавить рефреш кнопку. Может нам такое прикрутить ?

**Comment by sw-double** [comment]
чтобы не гонять одни и те же данные повторно, предлагаю реализовать кеширование метода `last` с помощью `ETag`, туда можно класть id самого последнего комментария

примерно так

```
etag = getLastCommentId()
if etag === request.headers[If-None-Match]
    return 304 Not Modified
...
...
...
response.headers[ETag] = etag
```

**Comment by sw-double** [comment]
то же самое кстати можно добавить и в метод `find` по такому же принципу

**Comment by umputun** [comment]
мы боремся с проблемой которую лучше и проще избежать убрав эту динамику вооще и заменив ее иконкой рефреш где-то тут 
<img width="551" alt="hd9b5-201906-02112123-u6g8j" src="https://user-images.githubusercontent.com/535880/58764078-9e263180-8528-11e9-8606-3d021fcf94af.png">

Меня напрягает не сколько техническая реализация, которая к такому просто не готова (remark42 не умеет пока стримить коменты), но фрагментарность этого решения которая будет работать только для одного из 3х элементов.

Еще раз пределагаю убрать динамику и заменить ее ручным рефрешем.

**Comment by sw-double** [comment]
насчет динамики понял

etag было бы полезно в любом случае, чтобы повторно не гонять данные – и при ручном рефреше, и как сейчас, и для запроса на аватарки

**Comment by umputun** [comment]
В принципе, идея эта интересная, однако мне кеширование rest со стороны клиента выглядит несколько странной и необычной затеей. T.e. бекенд делает разнообразное кеширование и сейчас и добавлять к нему второй слой кеширования звучит подозрительно избыточно. Но я подумаю над этим.
