### ISSUE TITLE
Возможность менять скорость воспроизведения

### ISSUE THREAD

**Issue by diimdeep** [radio-t/radio-t-site#61]

**Comment by umputun** [comment]
это, на мой взгляд не функция сайта и его проигрывателя. Пдобное реализовано во всех (многих?) podcast клиентах и я не понимаю зачем это надо на сайте.

**Comment by diimdeep** [comment]
Согласен что везде это есть по крайней мере на мобилках, но вот захотелось с лэптопа послушать. Зашел на сайт и тут не оказалось, в прочем не стал слушать через сайт, а закинул в VLC(он умеет менять скорость), но пришлось найти в ручную ссылку на mp3 из rss фида, т.к. на странице прямой ссылки не оказалось, кстате.

**Comment by umputun** [comment]
>  на странице прямой ссылки не оказалось
<img width="1181" alt="ftz5d_20190517_143144 a5j79" src="https://user-images.githubusercontent.com/535880/57951728-8e63e780-78b0-11e9-94f1-bf5a03a160df.png">

**Comment by diimdeep** [comment]
На новом сайте нет эти ссылок на рутовой странице, а есть только на страницах выпусков, на старом кажется были на рутовой тоже

**Comment by umputun** [comment]
это так, и это в свое время обсуждалось в процессе редизайна. Теперь эта ссылка на странице подкаста, но в любом случае ее не надо искать "в ручную ссылку на mp3 из rss фида"

**Comment by sattellite** [comment]
> Согласен что везде это есть по крайней мере на мобилках, но вот захотелось с лэптопа послушать.

Поддерживаю автора. Когда слушаю подкаст с мобильного устройства, то там скорость могу менять. С лэптопа слушаю прямо на сайте и скорость меняю через элемент `audio`, выставляю ему нужный `playbackRate`.
И как вариант можно попробовать реализовать это способом из Google Podcasts 
https://podcasts.google.com/?feed=aHR0cHM6Ly9yYWRpby10LmNvbS9wb2RjYXN0LnJzcw

**Comment by Modi34** [comment]
такое добавить 2 минуты
var audio = document.querySelectorAll('audio');
audio[1].playbackRate=2

![](https://i.imgur.com/7qIEUvz.gif)

**Comment by umputun** [comment]
очевидно, что этого недостаточно, но надо возможность выбора скорости в UI. Я продолжаю считать, что это не самая нужная фича, но если сможешь придумать/реализовать это правильно и ненавязчиво в UI, то PR welcome.

**Comment by webkonstantin** [comment]
https://github.com/radio-t/radio-t-site/pull/147
