### ISSUE TITLE
Темная тема сайта

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#62]
Это было в начальных планах на редизайн #26 но в релиз не попало. Хотельсь бы темную которая сама бы выбиралась на OS и браузерах где такое поддерживается и которую можно было бы переопределить ручным выбором.

**Comment by eshill** [comment]
Сама тема уже нарисована, то есть осталось прикрутить css, тумблер ручного переключения и написать скрипт автопереключения в зависимости от текущей темы в ОС.

**Comment by umputun** [comment]
ping @sw-double

**Comment by umputun** [comment]
круто, спасибо. Я правильно понимаю, что само он не умеет понимать какую показывать, т.е. только ручное опрделение? Или он не выбралось при переключении темы OS от того, что я до этого перключал руками?

**Comment by sw-double** [comment]
само не умеет, но сделать такое в целом можно (пока только для firefox и safari)

но после переключения руками тема сохраняется в браузере, и тема ОС уже иметь значения не будет

**Comment by umputun** [comment]
я думаю, этого вполне достаточно. палец не отвалится кликнуть один раз ;)
