### ISSUE TITLE
С включенным ghostery в FF не работает плеер подкастов

### ISSUE THREAD

**Issue by vblz** [radio-t/radio-t-site#64]
Должен ли проигрыватель работать с включенным ghostery? У меня при включенном ghostery не работает проигрывание, в логах ошибка `NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.`. Повторяется практически всегда, достаточно открыть главную страницу в новой вкладке и в ней запустить на проигрывание любой подкаст.
![изображение](https://user-images.githubusercontent.com/2076171/57948836-289d4d00-78fc-11e9-8efb-1da58c121365.png)

Перестает повторяться, если в Ghostery добавить сайт в доверенное, а потом удалить на этой же вкладке. При открытии сайта в новой вкладке проблема повторяется.

Браузер FF 66.0.5 (64-битный)
Ghostery для Firefox версии 8.3.4

**Comment by sw-double** [comment]
не знаю, связано это или нет, но хорошо бы еще mp3 файлы по https раздавать, иначе браузеры ругаются

**Comment by umputun** [comment]
раздавать только по https это, как показала практика, плохая идея. Я такое делаю у себя на сайте и получаю время от времени жалобы от андроидных пользователей про то, что их клиенты на такое ругаются. 

раздавать в дополнение - это можно. Надо только продумать автоматическую доставку сертификата на все раздающие узлы

**Comment by umputun** [comment]
вся раздача теперь по https из браузера, это как-то помогло проблеме тикета?

**Comment by vblz** [comment]
Не получается повторить, думаю, можно закрывать
