### ISSUE TITLE
"Part of this page is not secure" при включении онлайн-трансляции с главной https://radio-t.com

### ISSUE THREAD

**Issue by alff0x1f** [radio-t/radio-t-site#67]
Не знаю на сколько критично и существует ли стрим https, но когда находишься на главной radio-t.com, все секьюрно и зелёненько. Когда включаешь онлайн-стрим, замочек становится жёлтым со следующим комментарием:

>Loading mixed (insecure) display content “http://stream.radio-t.com/” on a secure page[Learn More] radio-t.com
>Loading mixed (insecure) display content “http://n9.radio-t.com/online” on a secure page[Learn More]

До #26, вроде, не было возможности слушать с главной страницы radio-t.com

**Comment by umputun** [comment]
> До #26, вроде, не было возможности слушать с главной страницы radio-t.com

Такая возможность всегда была.

**Comment by umputun** [comment]
Завершил процесс. Все загрузки сайта поменял на https и для свежих, архивов и стрима. Все "голые" http должны тоже работать.

Если кто заметит "Loading mixed (insecure) " - дайте знать

**Comment by umputun** [comment]
@sw-double каким-то образом замена на https поломала прыжки по врменным меткам в проигрывателе

**Comment by sw-double** [comment]
по http теперь тоже не работает

похоже сервер перестал отвечать на [Range запросы](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests)

рядом с `Content-Length` должно быть еще
```
Accept-Ranges: bytes
```

и на такой запрос должен уметь отвечать 206 Partial content вместо 200
```
curl https://n9.radio-t.com/rtfiles/rt_podcast649.mp3 -I -H "Range: bytes=0-1023"

HTTP/1.1 200 OK
Server: nginx
Date: Wed, 22 May 2019 22:38:48 GMT
Content-Type: audio/mpeg
Content-Length: 87295340
Last-Modified: Sun, 12 May 2019 17:38:23 GMT
Connection: keep-alive
ETag: "5cd85a0f-534056c"
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

я конфига nginx не видел, но возможно надо убрать такое `max_ranges 0;`

**Comment by umputun** [comment]
починил

**Comment by umputun** [comment]
полагаю, что никто не заметил "Loading mixed (insecure)" после починки, закрываю
