### ISSUE TITLE
Добавить num к response.

### ISSUE THREAD

**Issue by jordan1997** [radio-t/radio-t-site#69]
Добрый день
Пишу мобильное приложение для Radio-t. Есть маленькую просьба по API.
Добавьте в response на endPoints которые возвращают array подкастов field с номером выпуска. А то для того чтобы сделать call на `/podcast/{num}`, надо вытаскивать номер выпуска с `title`.

**Comment by umputun** [comment]
разумное предложение, добавил
<img width="564" alt="yz5to-201905-18175919-9abrb" src="https://user-images.githubusercontent.com/535880/57975803-bb8ac580-7996-11e9-8e52-ff826c14bb33.png">
