### ISSUE TITLE
Какого размера должны быть картинки чтоб так не обрезалось?

### ISSUE THREAD

**Issue by umputun** [radio-t/radio-t-site#71]
<img width="763" alt="z2l86-201905-18181232-qwt1n" src="https://user-images.githubusercontent.com/535880/57975877-9b5c0600-7998-11e9-8a0e-87c96b70eae1.png">

**Comment by sw-double** [comment]
квадрат, лучше 500–600px и не менее 250

**Comment by sw-double** [comment]
картинки все-таки маловаты, 190 пикс по меньшей стороне недостаточно, сильно пиксилезуются
