### ISSUE TITLE
В новом дизайне невозможно скачать запись без лишних переходов

### ISSUE THREAD

**Issue by Marcon** [radio-t/radio-t-site#72]
На мой взгляд, новый вариант сайта несколько неудобен.

Раньше можно было зайти на сайт, и прямо под плеером скачать запись подкаста. Теперь же для скачивания нужно сначала открыть страницу нужного выпуска подкаста, и уже там искать ссылку на аудио.

А если нужно скачать несколько записей, то приходится либо открыть выпуск>скачать>вернуться на страницу, либо пооткрывать выпуски в новых вкладках>переключить вкладку>скачать>закрыть вкладку.

**Comment by umputun** [comment]
@Khilkov @shvechikov  - может где-то тут расположить ссылку на файл? Не то чтоб это важно/критично, но если есть способ сделать это не нарушая дизайна, то было бы полезно в некоторых (редких) случаях 

<img width="1127" alt="rudwf-201905-19131459-updgn" src="https://user-images.githubusercontent.com/535880/57986265-6606f500-7a38-11e9-81b6-338c0c897efe.png">

@Marcon для подобного ручного скачивания многих файлов можно пойти прямо на http://archive.rucast.net/radio-t/media/

**Comment by eshill** [comment]
Не знаю насколько сложно добавить такую ссылку технически, с точки зрения дизайна смотрится ок.
![Group](https://user-images.githubusercontent.com/11502920/57986697-f23d0a80-7a80-11e9-819d-5ce4a5a9df07.png)

**Comment by Marcon** [comment]
@umputun Спасибо. Если решите, что добавление ссылки не стыкуется с дизайном, буду пользоваться предложенным workaround.
