### ISSUE TITLE
Блок "поделиться в соц сетях"

### ISSUE THREAD

**Issue by sazarkin** [radio-t/radio-t-site#90]
![image](https://user-images.githubusercontent.com/14792618/58817198-e2eabf00-8633-11e9-8a52-1fd9e50fbe1c.png)

Кажется, что эти кнопки должны предлагать поделиться ссылкой на конкретный пост, но сейчас все указывают на главную страницу.
Возможно, что этой библиотеке `ilyabirman-likely` не хватает параметров, и она дефолтится на текущий урл.

**Comment by umputun** [comment]
ping @sw-double
