### ISSUE TITLE
После нажатия на Show More страница скроллится к началу комментов

### ISSUE THREAD

**Issue by arsoba** [radio-t/radio-t-site#91]
Если открыта страница выпуска либо тем для выпуска с `#comments`, то после нажатия на Show More в комментах страница скролится к началу комментов.
Эта особенность появилась после фикса #73.
Фактически, тут https://github.com/radio-t/radio-t-site/blob/master/hugo/src/js/components/remark.tsx#L106

**Comment by umputun** [comment]
@sw-double похоже что это твое а не remark? Было бы круто починить

> It seems more like an issue of radio-t site than of remark. Guess remark component unmounts and remounts on particular events. The same thing does not happen, for example, on https://news.radio-t.com/post/temy-slushatelei-653

**Comment by umputun** [comment]
@Reeywhaar если можешь внести посильную помощь в починку этой интеграции, то я буду рад и слушатели будут счастливы  ;)

**Comment by umputun** [comment]
похоже, что фикс помог. @arsoba подтверждаешь?

Однако, перерсовки всего на света на каждое действия остались и это хотелось бы починить, если оно чинится.

**Comment by sw-double** [comment]
Перерисовка всего на свете на каждое действие = перерисовка страницы при нажатии на комментарий в боковой колонке, даже если уже находишься на нужной странице (вместо простого скролла до комментария)?

Ещё у меня вообще не работает скролл до нужного комментария при нажатии на коммент в боковой колонке на iOS, хотя раньше помню что работал. Возможно, тоже #73 сломал

**Comment by umputun** [comment]
> перерисовка страницы при нажатии на комментарий в боковой колонке, даже если уже находишься на нужной странице (вместо простого скролла до комментария)?

Нет, я не про эту перерисовку, но про ту, что происходит при действиях внутри коментов. Например, нажатие стрелок голосования приводит к миганию аватаров, подозреваю что они перерисовываются в этот момент. Такого не просиходит на [демо сайте](https://remark42.com/demo/), потому я подозреваю, что это что-то с связанное с сайтом радио-т.

**Comment by umputun** [comment]
> вообще не работает скролл до нужного комментария при нажатии на коммент в боковой колонке на iOS

у меня оно прыгает, просто не совсем точно, т.к. верхняя плашка прикрывает начало комента. Так, по моему было всегда с новым сайтом (после редизайна), я просто забывал пожаловаться ;)

Вот пример, прыгнуло на нужный комент, но его верхушка прикрыта 

<img width="396" alt="p1jz6_20190611_194405 3j1zf" src="https://user-images.githubusercontent.com/535880/59315881-4f436f00-8c81-11e9-9900-154d335fce3e.png">

**Comment by arsoba** [comment]
@umputun да, сейчас работает.
Сорри, что сам не добрался починить.
