### ISSUE TITLE
В новой теме плохо читается вложенность коментариев

### ISSUE THREAD

**Issue by alff0x1f** [radio-t/radio-t-site#94]
В старом интерфейсе комментарии были выровнены относительно левого края и первый уровень коментариев было четко видно. В новой теме #26 коментарии сдвинулись и теперь вложенность стала плохо читаться. 

Например вот тут можно подумать что комментарии 1го уровня:
![Screenshot from 2019-06-17 12-38-04](https://user-images.githubusercontent.com/3997330/59586685-ec2c5f00-90fc-11e9-921a-c37d1f9de1cb.png)

Когда просматриваю коментарии в новом интерфейсе, частенько принимаю коментарии 2го уровня за первый. Сейчас внимательно просмотрел скриншот, у второго уровня есть стрелочка, но это слишком неявно.

Возможно issue к remark42, не знаю куда правильнее отнести

**Comment by umputun** [comment]
я тоже сталкивался с подобным вопросом читая наши коменты. Я не уверен, что с этим можно что-сделать на уровне сайта, хотя @sw-double может меня поправить. На уровне remark42 мы как-то обсуждали подобное и одно из предложений было показывать вертикальными, едва заметными линиями уровни, примерно как это делается не reddit.

_К сожалению в remark42 у нас хроническая нехватка помощников, особенно со стороны UI. Героические усилия @Reeywhaar позволяют поддерживать и развивать frontend часть, но он там совсем один и его на все не хватает._

**Comment by umputun** [comment]
готово. @alff0x1f если удовлетворен результатом pls close
